### ISSUE TITLE
android 打包报错，请问有没有好的解决办法

### ISSUE THREAD

**Issue by Wesley-front-end** [easemob/im_flutter_sdk#100]
![360截图17060220044031](https://user-images.githubusercontent.com/30643443/77246507-e9016900-6c62-11ea-8c13-b465f8e23027.png)
support报错

**Comment by apex-wang** [comment]
#1.基本指令区
#-optimizationpasses 5
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-verbose
-ignorewarning
-printmapping proguardMapping.txt
#-optimizations !code/simplification/cast,!field/*,!class/merging/*
-dontoptimize
-keepattributes *Annotation*,InnerClasses
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable

#2.默认保留区
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class * extends android.view.View
-keep public class com.android.vending.licensing.ILicensingService
-keep class android.support.** {*;}

-keepclasseswithmembernames class * {
    native <methods>;
}
-keepclassmembers class * extends android.app.Activity{
    public void *(android.view.View);
}
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keep public class * extends android.view.View{
    *** get*();
    void set*(***);
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}
-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
-keep class **.R$* {
*;
}
-keepclassmembers class * {
    void *(**On*Event);
}

#3.webview
-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public *;
}
-keepclassmembers class * extends android.webkit.webViewClient {
    public void *(android.webkit.WebView, java.lang.String, android.graphics.Bitmap);
    public boolean *(android.webkit.WebView, java.lang.String);
}
-keepclassmembers class * extends android.webkit.webViewClient {
    public void *(android.webkit.webView, jav.lang.String);
}

-keep class * extends android.database.sqlite.** { *; }
-keep class com.hyphenate.chat.EMChatDB {*;}

-keep class com.hyphenate.chat.EMChatDB$* {
     *;
}

-keep class com.hyphenate.chat.core.EMConnectionManager* {*;}
-keepclassmembers class com.hyphenate.chat.core.EMDBManager$*{*;}
-keepclassmembers class com.hyphenate.chat.core.EMMonitorDB$*{*;}
#-keep class com.hyphenate.chat.* {*;}
-keep class com.hyphenate.chat.adapter.** {*;}
-keep class internal.org.apache.http.entity.** {*;}
-keep class org.apache.** {*;}
-keep class com.superrtc.** {*;}

#-keep class com.hyphenate.easeui.** {*;}

-keep class com.hyphenate.analytics.** {*;}
-keep class com.hyphenate.chat.EMCursorResult
-keep class com.hyphenate.chat.EMPageResult
-keep class com.hyphenate.chat.EMGroupInfo
这个图片上传的是不是有问题 我看不到 
打包可以试试切换到android项目后 在proguard-project加入混淆代码
support确保版本统一  如果有使用androidx 请将整个项目保持一致 不要和support混用

**Comment by Wesley-front-end** [comment]
什么时候发布可以支持androidx的插件，另外安卓demo里面的java下的代码需要添加到新项目吗，只用flutter的插件可以吗，现在打包可以了，但是运行会闪退

**Comment by apex-wang** [comment]
androidx 你现在可以直接下载到本地去依赖 然后把本地的support的依赖换成androidX的就可以了

**Comment by Wesley-front-end** [comment]
消息漫游咱们现在支持吗，如何使用消息漫游呢

**Comment by apex-wang** [comment]
漫游消息的API 我们之前都已经封装好了  漫游消息是增值服务 需要付费开通后才能用

**Comment by bingo** [comment]
@Mygithubyouknow 是否可以关闭了？
