### ISSUE TITLE
iOS编译报错

### ISSUE THREAD

**Issue by cv0cv0** [easemob/im_flutter_sdk#105]
<img width="290" alt="图片" src="https://user-images.githubusercontent.com/18623780/78626088-4da60000-78c0-11ea-9a9d-2dd2259f2cb9.png">

**Comment by FuDongHai** [comment]
将 MBProgressHUD的版本指定到1.1.0，然后在pod install
![image](https://user-images.githubusercontent.com/15087647/78637279-a8e5eb80-78dc-11ea-923a-7d5bec3bf3c6.png)
![image](https://user-images.githubusercontent.com/15087647/78637308-b26f5380-78dc-11ea-8936-9a6ece3ff006.png)

**Comment by cv0cv0** [comment]
> 将 MBProgressHUD的版本指定到1.1.0，然后在pod install
> ![image](https://user-images.githubusercontent.com/15087647/78637279-a8e5eb80-78dc-11ea-923a-7d5bec3bf3c6.png)
> ![image](https://user-images.githubusercontent.com/15087647/78637308-b26f5380-78dc-11ea-8936-9a6ece3ff006.png)

可以了，谢谢。

**Comment by cv0cv0** [comment]
@FuDongHai Android debug 模式可以运行，release 模式不可以运行。
<img width="1104" alt="图片" src="https://user-images.githubusercontent.com/18623780/78643599-1139ca80-78e7-11ea-9895-930f798bc787.png">
