### ISSUE TITLE
接收到消息怎么跳转到会话界面？

### ISSUE THREAD

**Issue by cv0cv0** [easemob/im_flutter_sdk#107]
找了下没找到这方面的逻辑。

**Comment by apex-wang** [comment]
接收到消息只能通过SDK提供的消息监听去接收  至于跳转聊天界面 可以通过Navigator.push进行跳转 
demo中是去跳转ChatPage页面 需要传的参数为 会话类型和对方的环信ID

**Comment by cv0cv0** [comment]
我想在收到推送的时候点击通知跳转到会话界面，如果 App 被杀掉了，需要去哪里监听？

**Comment by FuDongHai** [comment]
这个需要在原生（安卓和iOS）监听点击通知栏的系统方法，然后通过userinfo中"f"拿到发送消息方的环信id传给flutter层，最后在根据拿到的环信id跳转到聊天页面。

**Comment by cv0cv0** [comment]
> 这个需要在原生（安卓和iOS）监听点击通知栏的系统方法，然后通过userinfo中"f"拿到发送消息方的环信id传给flutter层，最后在根据拿到的环信id跳转到聊天页面。

好的，我研究一下。
