### ISSUE TITLE
iOS 编译 release 包报错

### ISSUE THREAD

**Issue by cv0cv0** [easemob/im_flutter_sdk#110]
<img width="290" alt="图片" src="https://user-images.githubusercontent.com/18623780/79555853-d1d36100-80d2-11ea-9104-365268a11d00.png">

**Comment by cv0cv0** [comment]
多编译几次又编译成功了。

**Comment by cv0cv0** [comment]
flutter 编译成功，但是在 Xcode 中打包报错。

**Comment by cv0cv0** [comment]
又不行了，就成功那一次。

**Comment by DouSN** [comment]
> 又不行了，就成功那一次。

请问问题解决了吗，我也遇到相同的问题了。。。

**Comment by cv0cv0** [comment]
@pingxiaodou 
<img width="1334" alt="图片" src="https://user-images.githubusercontent.com/18623780/79933041-7235d680-8481-11ea-9e08-a271b1d258b8.png">
两个都改为 no 。

**Comment by cv0cv0** [comment]
@pingxiaodou 但是 Android 用不了，这个 sdk 会导致 Android 闪退。

**Comment by DouSN** [comment]
@cv0cv0 感谢，终于能打包成功了。。我这里android上反而没有问题。demo中的视频通话和语音通话都是用原生实现的 需要把这里的代码和xml布局文件都复制到项目中
