### ISSUE TITLE
Android 登录成功之后闪退

### ISSUE THREAD

**Issue by cv0cv0** [easemob/im_flutter_sdk#113]
/chuangding.sho(14525): Rejecting re-init on previously-failed class java.lang.Class<internal.org.apache.http.entity.mime.MultipartEntity>: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/HttpEntity;
I/chuangding.sho(14525):   at void com.hyphenate.chat.adapter.EMAChatClient.native_login(java.lang.String, java.lang.String, boolean, boolean, com.hyphenate.chat.adapter.EMAError) ((null):-2)
I/chuangding.sho(14525):   at void com.hyphenate.chat.adapter.EMAChatClient.login(java.lang.String, java.lang.String, boolean, boolean, com.hyphenate.chat.adapter.EMAError) ((null):-1)
I/chuangding.sho(14525):   at void com.hyphenate.chat.EMClient$7.run() ((null):-1)
I/chuangding.sho(14525):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
I/chuangding.sho(14525):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
I/chuangding.sho(14525):   at void java.lang.Thread.run() (Thread.java:764)
I/chuangding.sho(14525): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.HttpEntity" on path: DexPathList[[zip file "/data/app/com.chuangding.shop-eKGlimzoFgNKepCMQQ5VbA==/base.apk"],nativeLibraryDirectories=[/data/app/com.chuangding.shop-eKGlimzoFgNKepCMQQ5VbA==/lib/arm64, /data/app/com.chuangding.shop-eKGlimzoFgNKepCMQQ5VbA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
I/chuangding.sho(14525):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/chuangding.sho(14525):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/chuangding.sho(14525):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/chuangding.sho(14525):   at void com.hyphenate.chat.adapter.EMAChatClient.native_login(java.lang.String, java.lang.String, boolean, boolean, com.hyphenate.chat.adapter.EMAError) ((null):-2)
I/chuangding.sho(14525):   at void com.hyphenate.chat.adapter.EMAChatClient.login(java.lang.String, java.lang.String, boolean, boolean, com.hyphenate.chat.adapter.EMAError) ((null):-1)

**Comment by apex-wang** [comment]
你这个异常是没找到apache.http下的类HttpEntity  是打包后运行的还是 直接debug运行的？ 顺便在看下android环境下有没有加这个库

**Comment by cv0cv0** [comment]
@Mygithubyouknow 是打包运行的。我没加，我以为 sdk 中加了。我看看 example 中的配置。

**Comment by apex-wang** [comment]
打包混淆开启了吗？ 代码里面应该是没有加混淆配置的
#1.基本指令区
#-optimizationpasses 5
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-verbose
-ignorewarning
-printmapping proguardMapping.txt
#-optimizations !code/simplification/cast,!field/*,!class/merging/*
-dontoptimize
-keepattributes *Annotation*,InnerClasses
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable

#2.默认保留区
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class * extends android.view.View
-keep public class com.android.vending.licensing.ILicensingService
-keep class android.support.** {*;}

-keepclasseswithmembernames class * {
    native <methods>;
}
-keepclassmembers class * extends android.app.Activity{
    public void *(android.view.View);
}
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keep public class * extends android.view.View{
    *** get*();
    void set*(***);
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}
-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
-keep class **.R$* {
*;
}
-keepclassmembers class * {
    void *(**On*Event);
}

#3.webview
-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public *;
}
-keepclassmembers class * extends android.webkit.webViewClient {
    public void *(android.webkit.WebView, java.lang.String, android.graphics.Bitmap);
    public boolean *(android.webkit.WebView, java.lang.String);
}
-keepclassmembers class * extends android.webkit.webViewClient {
    public void *(android.webkit.webView, jav.lang.String);
}

-keep class * extends android.database.sqlite.** { *; }
-keep class com.hyphenate.chat.EMChatDB {*;}

-keep class com.hyphenate.chat.EMChatDB$* {
     *;
}

-keep class com.hyphenate.chat.core.EMConnectionManager* {*;}
-keepclassmembers class com.hyphenate.chat.core.EMDBManager$*{*;}
-keepclassmembers class com.hyphenate.chat.core.EMMonitorDB$*{*;}
#-keep class com.hyphenate.chat.* {*;}
-keep class com.hyphenate.chat.adapter.** {*;}
-keep class internal.org.apache.http.entity.** {*;}
-keep class org.apache.** {*;}
-keep class com.superrtc.** {*;}

#-keep class com.hyphenate.easeui.** {*;}

-keep class com.hyphenate.analytics.** {*;}
-keep class com.hyphenate.chat.EMCursorResult
-keep class com.hyphenate.chat.EMPageResult
-keep class com.hyphenate.chat.EMGroupInfo

**Comment by cv0cv0** [comment]
@Mygithubyouknow 没有开启混淆，由于是纯 Flutter 项目。
