### ISSUE TITLE
数据库报错

### ISSUE THREAD

**Issue by cv0cv0** [easemob/im_flutter_sdk#114]
E/SQLiteDatabase(19857): Failed to open database '/storage/emulated/0/emlibs/libs/monitor.db'.
E/SQLiteDatabase(19857): android.database.sqlite.SQLiteException: not an error (code 0 SQLITE_OK): Could not open the database in read/write mode.
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:219)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:203)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:739)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:729)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:355)
E/SQLiteDatabase(19857): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
E/SQLiteDatabase(19857): 	at com.hyphenate.chat.core.EMMonitorDB.b(Unknown Source:6)
E/SQLiteDatabase(19857): 	at com.hyphenate.chat.EMClient.logout(Unknown Source:128)
E/SQLiteDatabase(19857): 	at com.hyphenate.chat.EMClient.logout(Unknown Source:13)
E/SQLiteDatabase(19857): 	at com.hyphenate.chat.EMClient$3.run(Unknown Source:4)

**Comment by apex-wang** [comment]
这个是sdk内部去调之前版本的SQLite抛出的异常  目前是不影响使用的 这个异常一直都存在
