### ISSUE TITLE
项目下载下来 flutter run 报错了

### ISSUE THREAD

**Issue by zhoutongbie** [easemob/im_flutter_sdk#117]
执行 flutter run 报以下错误  什么问题啊？

Running "flutter pub get" in example...                             0.9s
 
Launching lib/main.dart on iPhone 11 in debug mode...

Compiler message:
/usr/local/Cellar/flutter/.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-1.1.1/lib/src/cached_network_image_provider.dart:42:24:
Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/usr/local/Cellar/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11.

**Comment by zhoutongbie** [comment]
我下载的是dev版本。是需要下载release版本吗？

**Comment by FuDongHai** [comment]
看下这两个
https://github.com/easemob/im_flutter_sdk/issues/90
https://github.com/easemob/im_flutter_sdk/issues/105

**Comment by cv0cv0** [comment]
cached_network_image 库版本过低，在 pubspec.yaml 中添加：
```yaml
dependency_overrides:
  cached_network_image: ^2.0.0
```

**Comment by FuDongHai** [comment]
已经发版解决。
