### ISSUE TITLE
Android R 闪退

### ISSUE THREAD

**Issue by cv0cv0** [easemob/im_flutter_sdk#124]
E/linker  ( 9924): library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/apex/com.android.art/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/~~HN0j77CKjSilOMedejKk_g==/com.chuangding.shop-NcRL0JS5ZI72wXAPbB84WA==/lib/x86_64:/data/app/~~HN0j77CKjSilOMedejKk_g==/com.chuangding.shop-NcRL0JS5ZI72wXAPbB84WA==/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/user/0/com.chuangding.shop"]
W/System.err( 9924): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/user/0/com.chuangding.shop/app_lib/libsqlite.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62)
W/System.err( 9924): 	at java.lang.Runtime.load0(Runtime.java:939)
W/System.err( 9924): 	at java.lang.System.load(System.java:1625)
W/System.err( 9924): 	at internal.com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(Unknown Source:0)
W/System.err( 9924): 	at internal.com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(Unknown Source:182)
W/System.err( 9924): 	at internal.com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(Unknown Source:21)
W/System.err( 9924): 	at internal.com.getkeepsafe.relinker.ReLinker.loadLibrary(Unknown Source:5)
W/System.err( 9924): 	at internal.com.getkeepsafe.relinker.ReLinker.loadLibrary(Unknown Source:1)
W/System.err( 9924): 	at com.hyphenate.chat.EMClient._loadLibrary(Unknown Source:2)
W/System.err( 9924): 	at com.hyphenate.chat.EMClient._loadLibrary(Unknown Source:1)
W/System.err( 9924): 	at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source:7)
W/System.err( 9924): 	at com.hyphenate.chat.EMClient.init(Unknown Source:32)
W/System.err( 9924): 	at com.easemob.im_flutter_sdk.EMClientWrapper.init(EMClientWrapper.java:82)
W/System.err( 9924): 	at com.easemob.im_flutter_sdk.EMClientWrapper.onMethodCall(EMClientWrapper.java:45)
W/System.err( 9924): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err( 9924): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 9924): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err( 9924): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 9924): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err( 9924): 	at android.os.Looper.loop(Looper.java:183)
W/System.err( 9924): 	at android.app.ActivityThread.main(ActivityThread.java:7478)
W/System.err( 9924): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9924): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
W/System.err( 9924): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
W/System.err( 9924): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/user/0/com.chuangding.shop/app_lib/libhyphenate_av.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62)
W/System.err( 9924): 	at java.lang.Runtime.load0(Runtime.java:939)
W/System.err( 9924): 	at java.lang.System.load(System.java:1625)
W/System.err( 9924): 	at internal.com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(Unknown Source:0)
W/System.err( 9924): 	at internal.com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(Unknown Source:182)
W/System.err( 9924): 	at internal.com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(Unknown Source:21)
W/System.err( 9924): 	at internal.com.getkeepsafe.relinker.ReLinker.loadLibrary(Unknown Source:5)
W/System.err( 9924): 	at internal.com.getkeepsafe.relinker.ReLinker.loadLibrary(Unknown Source:1)
W/System.err( 9924): 	at com.hyphenate.chat.EMClient._loadLibrary(Unknown Source:2)
W/System.err( 9924): 	at com.hyphenate.chat.EMClient._loadLibrary(Unknown Source:1)
W/System.err( 9924): 	at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source:12)
W/System.err( 9924): 	at com.hyphenate.chat.EMClient.init(Unknown Source:32)
W/System.err( 9924): 	at com.easemob.im_flutter_sdk.EMClientWrapper.init(EMClientWrapper.java:82)
W/System.err( 9924): 	at com.easemob.im_flutter_sdk.EMClientWrapper.onMethodCall(EMClientWrapper.java:45)
W/System.err( 9924): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err( 9924): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 9924): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err( 9924): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 9924): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err( 9924): 	at android.os.Looper.loop(Looper.java:183)
W/System.err( 9924): 	at android.app.ActivityThread.main(ActivityThread.java:7478)
W/System.err( 9924): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9924): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
W/System.err( 9924): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/flutter ( 9924): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: dlopen failed: "/data/user/0/com.chuangding.shop/app_lib/libhyphenate.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62)
E/flutter ( 9924): 	at java.lang.Runtime.load0(Runtime.java:939)
E/flutter ( 9924): 	at java.lang.System.load(System.java:1625)
E/flutter ( 9924): 	at internal.com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(Unknown Source:0)
E/flutter ( 9924): 	at internal.com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(Unknown Source:182)
E/flutter ( 9924): 	at internal.com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(Unknown Source:21)
E/flutter ( 9924): 	at internal.com.getkeepsafe.relinker.ReLinker.loadLibrary(Unknown Source:5)
E/flutter ( 9924): 	at internal.com.getkeepsafe.relinker.ReLinker.loadLibrary(Unknown Source:1)
E/flutter ( 9924): 	at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source:19)
E/flutter ( 9924): 	at com.hyphenate.chat.EMClient.init(Unknown Source:32)
E/flutter ( 9924): 	at com.easemob.im_flutter_sdk.EMClientWrapper.init(EMClientWrapper.java:82)
E/flutter ( 9924): 	at com.easemob.im_flutter_sdk.EMClientWrapper.onMethodCall(EMClientWrapper.java:45)
E/flutter ( 9924): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/flutter ( 9924): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 9924): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/flutter ( 9924): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 9924): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 9924): 	at android.os.Looper.loop(Looper.java:183)
E/flutter ( 9924): 	at android.app.ActivityThread.main(ActivityThread.java:7478)
E/flutter ( 9924): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9924): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
E/flutter ( 9924): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/flutter ( 9924):
F/flutter ( 9924): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
F/libc    ( 9924): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9924 (chuangding.shop), pid 9924 (chuangding.shop)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86_64_arm64/generic_x86_64_arm64:10/RPP4.200409.015/6455311:userdebug/dev-keys'
Revision: '0'
ABI: 'x86_64'
Timestamp: 2020-05-07 14:54:46+0800
pid: 9924, tid: 9924, name: chuangding.shop  >>> com.chuangding.shop <<<
uid: 10150
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
'
    rax 0000000000000000  rbx 00000000000026c4  rcx 0000716567d32448  rdx 0000000000000006
    r8  000071656b1527f0  r9  000071656b1527f0  r10 00007ffe7a1a7e00  r11 0000000000000246
    r12 00007163950cd090  r13 0000716305149400  r14 00007ffe7a1a7df8  r15 00000000000026c4
    rdi 00000000000026c4  rsi 00000000000026c4
    rbp 0000000000000007  rsp 00007ffe7a1a7de8  rip 0000716567d32448
backtrace:
      #00 pc 000000000005a448  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+24) (BuildId: 0cb1ee2e4692086bd16b0cdb7620eb97)
      #01 pc 000000000005d40d  /apex/com.android.runtime/lib64/bionic/libc.so (abort+253) (BuildId: 0cb1ee2e4692086bd16b0cdb7620eb97)
      #02 pc 0000000001321500  /data/app/~~HN0j77CKjSilOMedejKk_g==/com.chuangding.shop-NcRL0JS5ZI72wXAPbB84WA==/lib/x86_64/libflutter.so (BuildId: 4498407751d9a010c8f62a3312593ff498e6f294)
      #03 pc 0000000001312b99  /data/app/~~HN0j77CKjSilOMedejKk_g==/com.chuangding.shop-NcRL0JS5ZI72wXAPbB84WA==/lib/x86_64/libflutter.so (BuildId: 4498407751d9a010c8f62a3312593ff498e6f294)
      #04 pc 00000000013111b2  /data/app/~~HN0j77CKjSilOMedejKk_g==/com.chuangding.shop-NcRL0JS5ZI72wXAPbB84WA==/lib/x86_64/libflutter.so (BuildId: 4498407751d9a010c8f62a3312593ff498e6f294)
      #05 pc 000000000135d7bc  /data/app/~~HN0j77CKjSilOMedejKk_g==/com.chuangding.shop-NcRL0JS5ZI72wXAPbB84WA==/lib/x86_64/libflutter.so (BuildId: 4498407751d9a010c8f62a3312593ff498e6f294)
      #06 pc 0000000001321d25  /data/app/~~HN0j77CKjSilOMedejKk_g==/com.chuangding.shop-NcRL0JS5ZI72wXAPbB84WA==/lib/x86_64/libflutter.so (BuildId: 4498407751d9a010c8f62a3312593ff498e6f294)
      #07 pc 00000000013263ec  /data/app/~~HN0j77CKjSilOMedejKk_g==/com.chuangding.shop-NcRL0JS5ZI72wXAPbB84WA==/lib/x86_64/libflutter.so (BuildId: 4498407751d9a010c8f62a3312593ff498e6f294)
      #08 pc 000000000001aa35  /system/lib64/libutils.so (android::Looper::pollInner(int)+1077) (BuildId: 502415e63ca3248a666763b1ca2d59c3)
      #09 pc 000000000001a59e  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+126) (BuildId: 502415e63ca3248a666763b1ca2d59c3)
      #10 pc 0000000000127053  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+35) (BuildId: bbfd6cd225dce70beef86960dce8af22)
      #11 pc 0000000000234386  /system/framework/x86_64/boot-framework.oat (art_jni_trampoline+182) (BuildId: 7fc56639bfc361a01712408a01b6fb02a496391e)
      #12 pc 0000000000178db4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+756) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #13 pc 000000000020cb56  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+246) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #14 pc 00000000003ac005  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+357) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #15 pc 00000000003a06c1  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1233) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #16 pc 0000000000791fc6  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+710) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #17 pc 0000000000163199  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+25) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #18 pc 0000000000392562  /system/framework/framework.jar (offset 0x927000) (android.os.MessageQueue.next+34)
      #19 pc 000000000078f594  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+2020) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #20 pc 0000000000163099  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+25) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #21 pc 0000000000391918  /system/framework/framework.jar (offset 0x927000) (android.os.Looper.loop+156)
      #22 pc 0000000000792ee7  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+1639) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #23 pc 0000000000163219  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+25) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #24 pc 00000000001a1f3e  /system/framework/framework.jar (android.app.ActivityThread.main+202)
      #25 pc 0000000000396c1f  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.13178773210012645589)+351) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #26 pc 000000000077a9c0  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1072) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #27 pc 000000000018434c  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+140) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #28 pc 0000000000179116  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+806) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #29 pc 000000000020cb75  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+277) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #30 pc 000000000062febe  /apex/com.android.art/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+5678) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #31 pc 000000000058df18  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+56) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #32 pc 000000000009afae  /apex/com.android.art/javalib/x86_64/boot.oat (art_jni_trampoline+222) (BuildId: 0e283f9cac599f57d802a9843d949820fe1a2807)
      #33 pc 0000000000178db4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+756) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #34 pc 000000000020cb56  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+246) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #35 pc 00000000003ac005  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+357) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #36 pc 00000000003a06c1  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1233) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #37 pc 000000000078f1c8  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1048) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #38 pc 0000000000163099  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+25) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #39 pc 000000000044cf4a  /system/framework/framework.jar (offset 0x1256000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
      #40 pc 0000000000396c1f  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.13178773210012645589)+351) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #41 pc 000000000077a9c0  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1072) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #42 pc 000000000018434c  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+140) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #43 pc 000000000095b7f7  /system/framework/x86_64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2039) (BuildId: 7fc56639bfc361a01712408a01b6fb02a496391e)
      #44 pc 0000000000179116  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+806) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #45 pc 000000000020cb75  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+277) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #46 pc 000000000062d5b7  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, __va_list_tag*)+487) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #47 pc 00000000004e2c69  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, __va_list_tag*)+665) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #48 pc 000000000041a390  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, __va_list_tag*, art::Primitive::Type, art::InvokeType)+2864) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #49 pc 00000000004090ae  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, __va_list_tag*)+30) (BuildId: ac7d906af99fd99289c2ce2a1072cf3e)
      #50 pc 00000000000afe68  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+168) (BuildId: bbfd6cd225dce70beef86960dce8af22)
      #51 pc 00000000000b8401  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+881) (BuildId: bbfd6cd225dce70beef86960dce8af22)
      #52 pc 0000000000004190  /system/bin/app_process64 (main+1648) (BuildId: d6b2621fa9c788320535274f35331797)
      #53 pc 0000000000050965  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+117) (BuildId: 0cb1ee2e4692086bd16b0cdb7620eb97)
Lost connection to device.
Exited (sigterm)

**Comment by apex-wang** [comment]
这应该是android项目那边有缓存问题 可以尝试清理缓存

**Comment by bingo** [comment]
@Mygithubyouknow close it?
