### ISSUE TITLE
Android 10 闪退

### ISSUE THREAD

**Issue by cv0cv0** [easemob/im_flutter_sdk#131]
W/System.err( 6257): java.lang.NullPointerException: Attempt to write to field 'java.lang.String com.hyphenate.chat.EMContact.username' on a null object reference
W/System.err( 6257): 	at com.hyphenate.chat.EMSessionManager.clearLastLoginUser(Unknown Source:6)
W/System.err( 6257): 	at com.hyphenate.chat.EMClient.logout(Unknown Source:24)
W/System.err( 6257): 	at com.hyphenate.chat.EMClient.logout(Unknown Source:13)
W/System.err( 6257): 	at com.hyphenate.chat.EMClient$3.run(Unknown Source:4)
E/AndroidRuntime( 6257): FATAL EXCEPTION: Thread-2
E/AndroidRuntime( 6257): Process: com.chuangding.shop, PID: 6257
E/AndroidRuntime( 6257): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.PowerManager$WakeLock.isHeld()' on a null object reference
E/AndroidRuntime( 6257): 	at com.hyphenate.chat.EMClient.logout(Unknown Source:43)
E/AndroidRuntime( 6257): 	at com.hyphenate.chat.EMClient.logout(Unknown Source:13)
E/AndroidRuntime( 6257): 	at com.hyphenate.chat.EMClient$3.run(Unknown Source:4)

**Comment by apex-wang** [comment]
sdk 退出时 底层有调用过powermanager相关操作 wakelok 是在init() 接口中获取的，也没有地方释放。所以这个问题还是没有初始化sdk导致的

**Comment by bingo** [comment]
@Mygithubyouknow close it?
