### ISSUE TITLE
官方demo报错

### ISSUE THREAD

**Issue by wva37254626** [easemob/im_flutter_sdk#135]
用android studio运行im_flutter_sdk 报错:
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️  Creating `android\settings_aar.gradle`...
[!] Flutter tried to create the file `android\settings_aar.gradle`, but failed.
To manually update `settings.gradle`, follow these steps:

    1. Copy `settings.gradle` as `settings_aar.gradle`
    2. Remove the following code from `settings_aar.gradle`:

            def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

            def plugins = new Properties()
            def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
            if (pluginsFile.exists()) {
                pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
            }

            plugins.each { name, path ->
                def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
                include ":$name"
                project(":$name").projectDir = pluginDirectory
            }

**Comment by apex-wang** [comment]
The built failed likely due to AndroidX incompatibilities in a plugin  是指插件中的AndroidX不兼容  检查一下是否有使用support库 或者是版本问题引起的？
