### ISSUE TITLE
iOS编辑报错

### ISSUE THREAD

**Issue by shaoting0730** [easemob/im_flutter_sdk#139]
iOS编辑报错
一开始出现
![image](https://user-images.githubusercontent.com/14305431/84980157-e334fa00-b163-11ea-85af-3e549802c9dd.png)
我修改为1.0.0
重新pod install 
出现
![image](https://user-images.githubusercontent.com/14305431/84980222-0d86b780-b164-11ea-9bb7-9a793e7ae626.png)

**Comment by dujiepeng** [comment]
请使用stable分支。
