### ISSUE TITLE
消息已送达，删除单条消息的功能能优先加上吗？

### ISSUE THREAD

**Issue by cy0131** [easemob/im_flutter_sdk#143]

**Comment by FuDongHai** [comment]
是指在聊天页面中添加删除单条消息的功能吗？
em_conversation.dart里面有提供删除消息的api，  void removeMessage(String messageId) {}

消息已送达------近期会考虑添加

**Comment by cy0131** [comment]
谢谢，我去看看，昨天翻了好久的文档都没找到

**Comment by cy0131** [comment]
请问 ” 消息已送达“  加上了吗？

**Comment by cy0131** [comment]
应该还有一个”消息已读“功能吧，这个我们也需要

**Comment by bingo** [comment]
@dujiepeng @FuDongHai keep tracking and update!

**Comment by caofuqing** [comment]
收到消息后 给对方发送反馈这个现在有了吗?

**Comment by dujiepeng** [comment]
请使用stable分支。
