### ISSUE TITLE
Flutter端支持自定义消息吗？

### ISSUE THREAD

**Issue by araisann** [easemob/im_flutter_sdk#145]
已经上线的web相关端，都是通过自定义消息在收发。     
看了看flutter端不支持自定义消息，自定义消息发过来，onMessageReceived的body都是null。

**Comment by apex-wang** [comment]
可以 考虑加到 ext扩展里面

**Comment by apex-wang** [comment]
目前android这边的自定义消息已经实现并提交  ios的近期也会完成并提交

**Comment by mingchaogui** [comment]
请尽快更新iOS SDK，需要用到。

**Comment by mingchaogui** [comment]
> 目前android这边的自定义消息已经实现并提交 ios的近期也会完成并提交

请尽快更新iOS SDK，需要用到。

**Comment by apex-wang** [comment]
自定义消息已经提交完毕

**Comment by bingo** [comment]
@Mygithubyouknow just close it! (Link pull request would be appreciated)
