### ISSUE TITLE
官方Demo报错 

### ISSUE THREAD

**Issue by lyyqyx** [easemob/im_flutter_sdk#146]
FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\lyy\FlutterGitSource\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 362

* What went wrong:
A problem occurred configuring project ':shared_preferences_linux'.
> Could not find method implementation() for arguments [project ':path_provider_linux'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by lyyqyx** [comment]
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\call\EMCallPlugin.java:40: ����: [deprecation] FlutterPluginBinding�е�getFlutterEngine()�ѹ�ʱ
        channel = new MethodChannel(binding.getFlutterEngine().getDartExecutor(), CALL, JSONMethodCodec.INSTANCE);
                                           ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\call\VideoCallActivity.java:151: ����: [deprecation] SoundPool�е�SoundPool(int,int,int)�ѹ�ʱ
            soundPool = new SoundPool(1, AudioManager.STREAM_RING, 0);
                        ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\call\VoiceCallActivity.java:106: ����: [deprecation] SoundPool�е�SoundPool(int,int,int)�ѹ�ʱ
			soundPool = new SoundPool(1, AudioManager.STREAM_RING, 0);
			            ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\conference\ConferenceActivity.java:176: ����: [deprecation] LayoutParams�е�FLAG_DISMISS_KEYGUARD�ѹ�ʱ
                | WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD
                                            ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\conference\ConferenceActivity.java:177: ����: [deprecation] LayoutParams�е�FLAG_SHOW_WHEN_LOCKED�ѹ�ʱ
                | WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED
                                            ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\conference\ConferenceActivity.java:178: ����: [deprecation] LayoutParams�е�FLAG_TURN_SCREEN_ON�ѹ�ʱ
                | WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON
                                            ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\conference\ConferenceActivity.java:448: ����: [deprecation] Resources�е�getColor(int)�ѹ�ʱ
                toolsPanelView.setBackgroundColor(getResources().getColor(R.color.color_transparent));
                                                                ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\conference\ConferenceActivity.java:463: ����: [deprecation] Resources�е�getColor(int)�ѹ�ʱ
                toolsPanelView.setBackgroundColor(getResources().getColor(R.color.bg_tools_panel));
                                                                ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\conference\ConferenceActivity.java:559: ����: �����ݵ�����: boolean�޷�ת��ΪEMStreamParam
                password, true, record, merge, new EMValueCallBack<EMConference>() {
                          ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\conference\EMConferencePlugin.java:38: ����: [deprecation] FlutterPluginBinding�е�getFlutterEngine()�ѹ�ʱ
        channel = new MethodChannel(binding.getFlutterEngine().getDartExecutor(), Conference, JSONMethodCodec.INSTANCE);
                                           ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\conference\EMConferencePlugin.java:107: ����: �Ҳ�������
        }else if(conference.getConferenceRole() == EMConferenceManager.EMConferenceRole.NoType){
                                                                                       ^
  ����:   ��� NoType
  λ��: �� EMConferenceRole
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\ImDemoPlugin.java:22: ����: [deprecation] FlutterPluginBinding�е�getFlutterEngine()�ѹ�ʱ
        channel = new MethodChannel(binding.getFlutterEngine().getDartExecutor(), CHANNEL, JSONMethodCodec.INSTANCE);
                                           ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\ImDemoPlugin.java:49: ����: �����ݵ�����: <����Runnable>�޷�ת��ΪConsumer<Void>
            post(new Runnable() {
                 ^
C:\Users\lyy\IM\im_flutter_sdk-dev\example\android\app\src\main\java\com\easemob\im_flutter_sdk_example\model\EaseCompat.java:12: ����: [deprecation] LayoutParams�е�TYPE_SYSTEM_ALERT�ѹ�ʱ
            return WindowManager.LayoutParams.TYPE_SYSTEM_ALERT;
                                             ^
ע: ĳЩ��Ϣ�Ѿ�����; ��ʹ�� -Xdiags:verbose ���±����Ի���������
3 ������
11 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by apex-wang** [comment]
第一个问题 可以参考https://stackoverflow.com/questions/63227732/a-problem-occurred-configuring-project-shared-preferences-linux  Flutter sdk版本太低了
第二次提交的 都是些警告 这个在新提交的版本中已经修改过时的api  部分api做了判断在高版本用新的api 旧版本还是用之前旧的api  run里面会提示警告但这并不会影响什么

**Comment by bingo** [comment]
@Mygithubyouknow Shall we just close this now?
