### ISSUE TITLE
请尽快更新pub版本

### ISSUE THREAD

**Issue by dreamfly32** [easemob/im_flutter_sdk#147]
用pub上的v1版本，首先会报minSdkVersion问题，改为19就可以了，接着还会报错，看图
![image](https://user-images.githubusercontent.com/32086491/88519038-0c2e9180-d024-11ea-88d5-a7cd0635dfc2.png)

换git拉取依赖的方式没问题。

文档稀碎就算了，起码得能用吧，估计开发人员是搞原生的吧，但是用flutter的人有多少会原生的，他们不懂配置问题，你们能不能写清楚点。看看隔壁融云，同样也是flutter版，要文档有文档，要回复有回复，要不是公司已经有业务在用，真想转了，唉~

**Comment by dujiepeng** [comment]
@dreamfly32 收到，近期会更新一版。
