### ISSUE TITLE
安卓编译报错

### ISSUE THREAD

**Issue by janjon** [easemob/im_flutter_sdk#148]
/Users/lzz/Documents/projects/openSource/im_flutter_sdk/android/src/main/java/com/easemob/im_flutter_sdk/EMChatRoomManagerWrapper.java:3: 错误: 程序包android.support.annotation不存在
import android.support.annotation.NonNull;
                                 ^
/Users/lzz/Documents/projects/openSource/im_flutter_sdk/android/src/main/java/com/easemob/im_flutter_sdk/EMChatRoomManagerWrapper.java:177: 错误: 找不到符号
    public void onMethodCall(@NonNull MethodCall methodCall, @NonNull MethodChannel.Result result) {
                              ^
  符号:   类 NonNull
  位置: 类 EMChatRoomManagerWrapper
/Users/lzz/Documents/projects/openSource/im_flutter_sdk/android/src/main/java/com/easemob/im_flutter_sdk/EMChatRoomManagerWrapper.java:177: 错误: 找不到符号
    public void onMethodCall(@NonNull MethodCall methodCall, @NonNull MethodChannel.Result result) {
                                                              ^
  符号:   类 NonNull
  位置: 类 EMChatRoomManagerWrapper
3 个错误

**Comment by apex-wang** [comment]
我们EMChatRoomManagerWrapper里面没有用到v4啊

**Comment by apex-wang** [comment]
我们新发的版本都是用的androidx 你可以全部把support切换到androidx  或者重新拉最新的版本下来
