### ISSUE TITLE
清空聊天记录无效

### ISSUE THREAD

**Issue by mingchaogui** [easemob/im_flutter_sdk#150]
EMConversation.clearAllMessages()，重新加载消息依然存在。

**Comment by apex-wang** [comment]
我这边调自己demo的api 会话对象的本地聊天记录都会被删除 除非你那边是调拉去漫游消息的api  重新加载从服务端拉取的消息

**Comment by mingchaogui** [comment]
> 我这边调自己demo的api 会话对象的本地聊天记录都会被删除 除非你那边是调拉去漫游消息的api 重新加载从服务端拉取的消息

这个问题仅在iOS上出现，Android是没问题

**Comment by mingchaogui** [comment]
目前暂时先通过删除会话再重新创建的方式来清除聊天记录

**Comment by mingchaogui** [comment]
> 我这边调自己demo的api 会话对象的本地聊天记录都会被删除 除非你那边是调拉去漫游消息的api 重新加载从服务端拉取的消息

目前还发现一个问题是，clearAllMessages会导致会话被删除，下次loadAllConversations不会在加载到这个会话

**Comment by bingo** [comment]
@dujiepeng 麻烦看下iOS侧的问题

**Comment by apex-wang** [comment]
![22](https://user-images.githubusercontent.com/22721647/94220951-bf304400-ff1c-11ea-9134-b9e75588172a.png)

**Comment by mingchaogui** [comment]
就是clearAllMessages，今天测试问题依旧存在

**Comment by mingchaogui** [comment]
@dujiepeng @Mygithubyouknow 可以关注下这个问题吗

**Comment by apex-wang** [comment]
@mingchaogui clearAllMessages的问题是ios测设置不生效还是什么问题？ 上次这个问题描述目前还发现一个问题是，clearAllMessages会导致会话被删除，下次loadAllConversations不会在加载到这个会话。
我截图有注释的clearAllMessages会清除数据库和内存中的消息  clear只清除内存的，不清除db的消息

**Comment by mingchaogui** [comment]
> @mingchaogui clearAllMessages的问题是ios测设置不生效还是什么问题？ 上次这个问题描述目前还发现一个问题是，clearAllMessages会导致会话被删除，下次loadAllConversations不会在加载到这个会话。
> 我截图有注释的clearAllMessages会清除数据库和内存中的消息 clear只清除内存的，不清除db的消息

最新确认的是，我在iOS上使用clearAllMessages但并没有清除db。

**Comment by dujiepeng** [comment]
请使用stable分支。
