### ISSUE TITLE
Android离线推送无法集成

### ISSUE THREAD

**Issue by 17y** [easemob/im_flutter_sdk#151]
作为非Android developer配置离线推送真的太难了

本身项目有推送需求 用的是MobPush
现在在Manifest中配置 
`<meta-data
            android:name="com.huawei.hms.client.appid"
            android:value="appid=102307921"/>`
但是在执行过程中读取到的是 "102307921" 根据环信SDK的读取方法 既没有"="也不是Int 最终读到的值是0 

W/Bundle: Key com.huawei.hms.client.appid expected Integer but value was a java.lang.String.  The default value 0 was returned.

求助一下T.T

**Comment by apex-wang** [comment]
试试如果将mobpush的配置先注释了  直接在环信这边进行配置 获取到的appid是什么
