### ISSUE TITLE
EMConversation里的extField请加上set方法

### ISSUE THREAD

**Issue by once10301** [easemob/im_flutter_sdk#157]

**Comment by apex-wang** [comment]
extField 非私有属性 通过EMConversation对象就可以调用 并赋值

**Comment by once10301** [comment]
直接赋值以后用EMClient.getInstance().chatManager().getAllConversations()取出来的EMConversation里的extField还是空字符串，我需要用这个字段来做置顶操作

**Comment by apex-wang** [comment]
好的 我明白你的意思了 直接赋值只是给flutter这边赋值 getAllConversations是从原生那边获取将数据传递给flutter 这时候是拿不到扩展属性的 这个我们这边加一下

**Comment by once10301** [comment]
嗯嗯，非常感谢，加上以后可不可以来这边通知我一下

**Comment by apex-wang** [comment]
Flutter 和 android这边都已实现  等ios同事加一下就行了
