### ISSUE TITLE
iOS设置apns证书名的问题

### ISSUE THREAD

**Issue by AcYangle** [easemob/im_flutter_sdk#161]
作者请教一下
void initIM() {
    EMOptions options = new EMOptions(appKey: Config.getIMAPPKey());
    EMPushConfig config = new EMPushConfig();
    config.enableAPNS(Config.getIMApns());
    config.enableMiPush(
        Config.getXiaoMiPushAppId(), Config.getXiaoMiPushAppKey());
    config.enableHWPush();
    options.setPushConfig(config);
    EMClient.getInstance().init(options);
    EMClient.getInstance().setDebugMode(true);
    EMClient.getInstance().addConnectionListener(this);
    EMClient.getInstance().chatManager().addMessageListener(this);

    EMClient.getInstance().callManager().registerCallSharedManager();
    EMClient.getInstance()
        .conferenceManager()
        .registerConferenceSharedManager();
  }
这是我初始化环信SDK的方法
初始化后安卓能正常收到离线推送，但是iOS部分测试机能收到，部分收不到，
经我排查，发现环信控制台im用户下出现部分用户证书项未为空，
以前做iOS原生开发时，SDK有提供updatePushNotificationOptionsToServerWithCompletion接口，
我在登陆成功后调用这个接口更新SDK的config，
但flutter版本我找了一下，并没有找到此接口，能否帮我解答一下

**Comment by AcYangle** [comment]
![image](https://user-images.githubusercontent.com/15205440/94097756-b0348d80-fe59-11ea-8238-663e4ab24c54.png)
![image](https://user-images.githubusercontent.com/15205440/94097944-1caf8c80-fe5a-11ea-90f4-4a85bce4ee5f.png
最近又发现一个情况，我用图一代码设置推送为发送详细内容，图2中的信息可看出，iOS测试机能够设置上，安卓测试机不成功，另外图二也标出了iOS丢失apns证书的情况，此问题已困扰我许久，希望能够尽快帮助我解决或排查一下，谢谢了

**Comment by apex-wang** [comment]
![1111](https://user-images.githubusercontent.com/22721647/94236543-fe23c100-ff3f-11ea-9609-d1a653701aac.png)
android不成功是因为之前android原生那边的sdk中 没有这个api   android这个api是后面才加上的 flutter这边还没更新

**Comment by AcYangle** [comment]
收到，感谢回复，iOS方面的问题，我已提取日志文件提交到工单回复

**Comment by apex-wang** [comment]
新加的api 我们这边后面都会加上

**Comment by AcYangle** [comment]
近期有更新计划吗

**Comment by dujiepeng** [comment]
@AcYangle 有，会优先把这几个isuees修复。
