### ISSUE TITLE
集成华为推送，没有收到错误码。但是token 没有注册成功。

### ISSUE THREAD

**Issue by Yanxiaohu** [easemob/im_flutter_sdk#163]
日志里只能收到，下面两条提示。

[EMPushHelper] isSupportPush: HMSPUSH - true
[EMPushHelper] EMPushHelper register, prefer push type: HMSPUSH

**Comment by apex-wang** [comment]
华为注册token的代码需要你这边在原生成功登录后去调用

**Comment by apex-wang** [comment]
华为官方有提供对应的插件 可以直接从flutter这边获取devicetoken 我们有封装一个上传token的接口 你获取到华为devicetoken之后调上传的接口给环信服务即可 这个操作需要在登录环信之后去上传
