### ISSUE TITLE
集成环信后，apk增加50多M，有办法减小apk吗？

### ISSUE THREAD

**Issue by niteapps** [easemob/im_flutter_sdk#165]
集成环信，没有加推送，只是打包'arm64-v8a', 'armeabi-v7a'两种，没有加x86, apk文件仍增加了50多M。

用sdk里面的demo example编译打包，也有52M（去掉推送功能，没有包含x86）

请问有什么办法可以减小apk吗？ 本来apk才30M，增加环信就到了80多M了

**Comment by niteapps** [comment]
如果只打包 'armeabi-v7a'，我原来apk大小11M，增加环信后也达到了34M多

**Comment by apex-wang** [comment]
你是本地单独依赖的jar和so吗？我们的so分为lite版和av版  
lite版指不包含音视频的so 这个会相对小点 可以自己在官网下载so去查看大小
av版指包含音视频的so 音视频的so文件都比较大 armeabi-v7a 大概6.5mb  arm64-v8a大概10.6mb 
x86大概11.6mb  x86_64大概 11.7mb
如果要控制大小 可以先看自己是否需要用到音视频相关的功能 如果不需要可以使用lite版的so 这样可以减少很多
如果需要用音视频 可以选择合适的CPU架构类型的so 多余或者用不到的可以全部去掉  打包时配置混淆减少apk体积

**Comment by niteapps** [comment]
不是本地单独依赖jar和so，直接git  im_flutter_sdk。
im_flutter_sdk是依赖的api 'com.hyphenate:hyphenate-sdk:3.7.1'吧

**Comment by apex-wang** [comment]
远程仓库这个是用的av版so 肯定比较大  原生那边可以替换成jar和so依赖 自行控制加载cpu架构类型so  打包时在加上混淆
