### ISSUE TITLE
调用loginWithToken出现sdk内部错误 [JSONException] No value for password

### ISSUE THREAD

**Issue by baohangxing** [easemob/im_flutter_sdk#166]
```dart
   ImTokenBean imToken = await ImRequest.getImToken()
        .then((value) => ImTokenBean.fromJson(value));

    if (imToken.accessToken == null) {
      Toast.toast(context, msg: '聊天模块登录失败，获取token失败');
      return;
    }
    print(imToken.user.username + imToken.accessToken);

    ///TODO
    EMClient.getInstance().loginWithToken(
        imToken.user.username, imToken.accessToken, onSuccess: () {
      print("login succes");
    }, onError: (code, desc) {});
```

I/flutter (11230): ============================================ 请求数据 ================================================
I/flutter (11230): data = null
I/flutter (11230): queryParameters = {}
I/flutter (11230): method = POST
I/flutter (11230): headers = {Content-Type: application/json, Authorization: Bearer aeb58c11-cd0e-4856-8d07-e052467ffe2d}
I/flutter (11230): 
I/flutter (11230): ============================================ 响应数据 ================================================
I/flutter (11230): code = 200
I/flutter (11230):  v  — — — — — — — — — — — — — — — — st — — — — — — — — — — — — — — — —
I/flutter (11230):  v | data = {code: 0, success: true, msg: SUCCESS, data: {access_token: YWMtW4R-tgLxEeuoAOuYjSOVbaz-KlCL9
I/flutter (11230):  v | BHpheEx79Zh4X1ORbFQ_tkR6pYXh3MNUmEjAwMAAAF03fwb7wBPGgCHQUW65gNSXeeaW7wnZ-K5CmbhuM1WeNpXkZtMJBhs0A, e
I/flutter (11230):  v | xpires_in: 5184000, user: {created: 1601001986283, modified: 1601001986283, type: user, uuid: 4e45b1
I/flutter (11230):  v | 50-fed9-11ea-9617-87730d526123, username: 89364, activated: true}}}
I/flutter (11230):  v  — — — — — — — — — — — — — — — — ed — — — — — — — — — — — — — — — —
I/flutter (11230):
I/flutter (11230):
I/flutter (11230): 89364YWMtW4R-tgLxEeuoAOuYjSOVbaz-KlCL9BHpheEx79Zh4X1ORbFQ_tkR6pYXh3MNUmEjAwMAAAF03fwb7wBPGgCHQUW65gNSXeeaW7wnZ-K5CmbhuM1WeNpXkZtMJBhs0A
D/ONE SDK (11230): [2020/09/30 15:50:24:176]: [JSONException] No value for password
I/flutter (11230):

**Comment by apex-wang** [comment]
不好意思 这里是调错api了  您这边可以先在em_client.dart里面换一下EMSDKMethod.loginWithToken​  我们这边已经修改过了 下次提交代码会同步上去

**Comment by baohangxing** [comment]
嗯好
