### ISSUE TITLE
调用getUnreadMessageCount()方法后没有返回，也没有报错。

### ISSUE THREAD

**Issue by sec7et** [easemob/im_flutter_sdk#167]
em_chat_manager.dart文件下，
```
  /// 获取未读消息的计数。
  Future<int> getUnreadMessageCount() async {
    Map<String, dynamic> result = await _emChatManagerChannel.invokeMethod(EMSDKMethod.getUnreadMessageCount);
    if (result['success']) {
      return result['count'];
    } else {
      return 0;
    }
  }
```

Map<String, dynamic> result = await _emChatManagerChannel.invokeMethod(EMSDKMethod.getUnreadMessageCount);
主要是这段代码突然获取不到返回值了，在 result这行 和下面的 if 判断 都打了断点，发现无法进入到 if 这一行的断点去。有什么问题会导致这情况发生吗？

**Comment by apex-wang** [comment]
你这边可以先切换到android 然后在EMChatManagerWrapper中断点 看flutter这边有没有通过onMethodCall去调用原生getUnreadMessageCount方法 或者说这中途有遇见什么错误 原生获取到数据后通过result返回给flutter
![截图](https://user-images.githubusercontent.com/22721647/95653556-24468500-0b2c-11eb-8df2-a3187ad8bc96.png)

**Comment by sec7et** [comment]
> 你这边可以先切换到android 然后在EMChatManagerWrapper中断点 看flutter这边有没有通过onMethodCall去调用原生getUnreadMessageCount方法 或者说这中途有遇见什么错误 原生获取到数据后通过result返回给flutter
> ![截图](https://user-images.githubusercontent.com/22721647/95653556-24468500-0b2c-11eb-8df2-a3187ad8bc96.png)

OK，后来我检查了，发现是iOS这边的EMChatManagerWrapper中，没有实现获取未读消息数的方法，有点尴尬。自己实现了一下。

**Comment by apex-wang** [comment]
好的 感谢您的反馈 我这边已经修复了 下一次发版会加上

**Comment by sec7et** [comment]
> 好的 感谢您的反馈 我这边已经修复了 下一次发版会加上

好的，辛苦了，谢谢。
