### ISSUE TITLE
ios 编译失败

### ISSUE THREAD

**Issue by surfsky** [easemob/im_flutter_sdk#168]
[!] CocoaPods could not find compatible versions for pod "im_flutter_sdk":
      In Podfile:
        im_flutter_sdk (from `.symlinks/plugins/im_flutter_sdk/ios`)

    Specs satisfying the `im_flutter_sdk (from `.symlinks/plugins/im_flutter_sdk/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by surfsky** [comment]
有谁解答一下吗？示例程序编译不通过，不知道怎么玩，可能就要换其它 IM 服务了

**Comment by dujiepeng** [comment]
@surfsky 有执行flutter packages get 么？

**Comment by surfsky** [comment]
执行了 flutter packages get 

改了platform :ios, '9.0' 后错误变为

CocoaPods could not find compatible versions for pod "flutter_sound":
      In Podfile:
        flutter_sound (from `.symlinks/plugins/flutter_sound/ios`)

    Specs satisfying the `flutter_sound (from `.symlinks/plugins/flutter_sound/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by surfsky** [comment]
感觉就是依赖有问题，怎么配置pod都出错，能否调测修正一下？我是新手，实在无解，谢谢

**Comment by dujiepeng** [comment]
@surfsky 试试修改example项目pubspec.yaml的flutter_sound为4.0版本
dependencies:
  flutter_sound: ^4.0.0

**Comment by baobaocui** [comment]
1.需要把podfile里面改为  platform :ios, '10.0'。因为flutter_sound最低支持9.3
2.用xcode打开Runner项目。TARGETS-General-Deployment Info 里把版本改为最低支持10.0
