### ISSUE TITLE
消息没有默认推送

### ISSUE THREAD

**Issue by panzhoutao** [easemob/im_flutter_sdk#169]
消息到达没有消息提醒

**Comment by apex-wang** [comment]
目前的版本ui中还未实现 消息通知栏这部分功能 后期我们会加上  这个在线消息通知实际上是调本地通知的方法  我们这边暂时只做了第三方离线推送通知的功能  可以看看这个flutter_local_notifications插件 后期我们应该会用该插件来实现 或者我们自己封装

**Comment by AcYangle** [comment]
请问这个问题什么时候更新呀

> 目前的版本ui中还未实现 消息通知栏这部分功能 后期我们会加上 这个在线消息通知实际上是调本地通知的方法 我们这边暂时只做了第三方离线推送通知的功能 可以看看这个flutter_local_notifications插件 后期我们应该会用该插件来实现 或者我们自己封装

**Comment by niyangup** [comment]
> 目前的版本ui中还未实现 消息通知栏这部分功能 后期我们会加上 这个在线消息通知实际上是调本地通知的方法 我们这边暂时只做了第三方离线推送通知的功能 可以看看这个flutter_local_notifications插件 后期我们应该会用该插件来实现 或者我们自己封装

啥时候更新鸭

**Comment by apex-wang** [comment]
不好意思 这个估计还得等一段时间 我们这边近期是在改sdk方面之前写的不太合理的地方 并且新发了一个分支alpha， ui和 缺失的部分功能 我们后期会补上

**Comment by TerryAsh** [comment]
ios 推送消息接受有什么办法吗

**Comment by dujiepeng** [comment]
请使用stable分支。
