### ISSUE TITLE
撤回消息失败，code 500

### ISSUE THREAD

**Issue by mingchaogui** [easemob/im_flutter_sdk#170]
desc: Message is invalid

**Comment by apex-wang** [comment]
您好 消息无效 您这边可以把要撤回的这个message打印一下 看看这个message是否有问题

**Comment by apex-wang** [comment]
检查一下 message is invalid 是消息id 或者body 为空，或者from不是登录用户时提示的

**Comment by mingchaogui** [comment]
![20201014160205](https://user-images.githubusercontent.com/5003855/95960709-aa1d4580-0e36-11eb-8679-9d667d03522f.jpg)

现在是无Success也无Error回调了。EMMessage对象如图。

**Comment by mingchaogui** [comment]
![20201014163340](https://user-images.githubusercontent.com/5003855/95964118-0aae8180-0e3b-11eb-8b92-61a9f4de04ee.jpg)

注意到刚才的消息没有_conversationId，这是重新从数据库载入后的。问题一样。

**Comment by mingchaogui** [comment]
我们的环信是企业版服务

**Comment by apex-wang** [comment]
这块处理有点问题 我们这边下个版本进行修复并提交 或者你可以自己先改一下 撤回是增值服务 需要有开通此功能才可以用

![截图1](http://user-images.githubusercontent.com/22721647/96398464-870be080-11fe-11eb-8862-da6ab14d2bdd.png)

**Comment by dujiepeng** [comment]
请使用stable分支。
