### ISSUE TITLE
ios自定义消息params为null

### ISSUE THREAD

**Issue by panzhoutao** [easemob/im_flutter_sdk#172]
安卓正常，但是ios的params是null

**Comment by apex-wang** [comment]
你ios params传的类型是String的吗？  原生那边该参数类型为Map<String,String>

**Comment by panzhoutao** [comment]
> 你ios params传的类型是String的吗？ 原生那边该参数类型为Map<String,String>

是，安卓是正常的，只有ios不行

**Comment by apex-wang** [comment]
是用的最新提交的代码吗？

**Comment by panzhoutao** [comment]
> 是用的最新提交的代码吗？

是的

**Comment by dujiepeng** [comment]
只支持<String, Stringl>类型。
