### ISSUE TITLE
iOS端发送自定义消息，接收方收不到非String类型的value

### ISSUE THREAD

**Issue by mingchaogui** [easemob/im_flutter_sdk#173]

**Comment by mingchaogui** [comment]
这个Bug应该是最近更新才出现的，之前版本测试没发现此问题。可以紧急修复下吗？

**Comment by dujiepeng** [comment]
@mingchaogui 你好，发送的内容是什么？

**Comment by mingchaogui** [comment]
> @mingchaogui 你好，发送的内容是什么？

类似这样的数据，接收端只能接收到String类型的值
{
"boolTest": false,
"intTest": 1,
"doubleTest": 1.0,
"id": "abcd",
}

**Comment by mingchaogui** [comment]
到接收端就剩下
{
"id": "abcd",
}

**Comment by dujiepeng** [comment]
@mingchaogui 刚查了下，这个是ios sdk的问题。 不是flutter层的，所以要等ios sdk修复。 您如果比较紧急可以先转成string，sdk更新后我会在这里回复。

**Comment by dujiepeng** [comment]
@mingchaogui  刚刚和同事确认了，custom消息中的params只支持string类型。故此暂不做修复。
