### ISSUE TITLE
小米推送、Vivo推送的通知显示不正确

### ISSUE THREAD

**Issue by mingchaogui** [easemob/im_flutter_sdk#177]
如图，标题和内容皆为“用户：消息“。TItle正确值应为用户名，正文为消息。
APNS则正常。

![Screenshot_2020-11-03-20-06-02-184_com miui home](https://user-images.githubusercontent.com/5003855/97983559-6d7ab380-1e10-11eb-9da1-c2fd1f2f2266.jpg)

**Comment by apex-wang** [comment]
Android和ios的实现不同 android的是title+content的方式 而ios只有一个content 通过api去显示详情 android这边默认title和content一样 如果需要区分 可以自己在发消息的时候加上对应的扩展字段em_push_name和em_push_content去展示

**Comment by mingchaogui** [comment]
> Android和ios的实现不同 android的是title+content的方式 而ios只有一个content 通过api去显示详情 android这边默认title和content一样 如果需要区分 可以自己在发消息的时候加上对应的扩展字段em_push_name和em_push_content去展示

自定义push_name和push_content后，apns又只能看到content了。有什么兼容的办法吗？另外，还有其他可以自定义的扩展字段吗？

**Comment by mingchaogui** [comment]
> Android和ios的实现不同 android的是title+content的方式 而ios只有一个content 通过api去显示详情 android这边默认title和content一样 如果需要区分 可以自己在发消息的时候加上对应的扩展字段em_push_name和em_push_content去展示

https://stackoverflow.com/questions/8320065/setting-the-title-of-a-push-notification
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification

查阅资料得知iOS是可以支持Title设置的，我看到很多APP通知也是有Title的，希望环信这边可以支持一下。

**Comment by dujiepeng** [comment]
https://github.com/easemob/im_flutter_sdk/issues/235#issue-811702723
