### ISSUE TITLE
打包开启混淆，直接闪退，不调用环信初始化正常

### ISSUE THREAD

**Issue by dante312** [easemob/im_flutter_sdk#178]

**Comment by apex-wang** [comment]
您好 混淆文件您这边是怎么配置的？闪退的时候报的异常信息可以提供一下我们看看

**Comment by dante312** [comment]
已解决，在混淆文件中添加如下，打包后正常，谢谢！
-keep class com.hyphenate.chat.core.EMConnectionManager* {*;}
-keepclassmembers class com.hyphenate.chat.core.EMDBManager${*;}
-keepclassmembers class com.hyphenate.chat.core.EMMonitorDB${*;}
#-keep class com.hyphenate.chat. {;}
-keep class com.hyphenate.chat.adapter.** {*;}
-keep class internal.org.apache.http.entity.** {*;}
-keep class org.apache.** {*;}
-keep class com.superrtc.** {*;}

#-keep class com.hyphenate.easeui.** {*;}

-keep class com.hyphenate.analytics.** {*;}
-keep class com.hyphenate.chat.EMCursorResult
-keep class com.hyphenate.chat.EMPageResult
-keep class com.hyphenate.chat.EMGroupInfo
