### ISSUE TITLE
iOS9 pod install报错，提示SDK必须高于该版本，当前版本不支持iOS9了吗

### ISSUE THREAD

**Issue by Feng3364** [easemob/im_flutter_sdk#179]
最新代码拉下来
使用本地SDK：podfile里面改成platform :ios, '9.0'->pod install报错
![image](https://user-images.githubusercontent.com/33592584/101127272-2f9fc380-3638-11eb-8e4d-9c030b276f4b.png)

使用git-url：运行报错
![image](https://user-images.githubusercontent.com/33592584/101128106-ed778180-3639-11eb-9a0c-eebb38ac34c3.png)

**Comment by ixre** [comment]
只能最低10.0

**Comment by dujiepeng** [comment]
alpha分支可以使用9.0
