### ISSUE TITLE
Flutter alpha版本无法监听消息是否发送成功

### ISSUE THREAD

**Issue by jb522185660** [easemob/im_flutter_sdk#186]
通过EMClient.getInstance.chatManager.sendMessage如何监听消息发送成功，这个方法的回调里面返回的消息信息里面，消息的状态是EMMessageStatus.CREATE。
master 版本里面，可以通过onSuccess可以监听消息发送成功
另外发送视频语音消息，又是如何监听发送的进度？

**Comment by dujiepeng** [comment]
这个listener放到了EMMessage中，这样的实现主要是因为考虑到，只更新消息对应的widget就可以，而不需要刷新全部的ChatPage


`EMMessageStatusListener listener;`

```
abstract class EMMessageStatusListener {
  /// 消息进度
  void onProgress(int progress) {}

  /// 消息发送失败
  void onError(EMError error) {}

  /// 消息发送成功
  void onSuccess() {}

  /// 消息已读
  void onReadAck() {}

  /// 消息已送达
  void onDeliveryAck() {}

  /// 消息状态发生改变
  void onStatusChanged() {}
}
```
