### ISSUE TITLE
Flutter alpha版本，发送视频消息成功以后，获取的消息body缺少内容

### ISSUE THREAD

**Issue by jb522185660** [easemob/im_flutter_sdk#187]
您好，发送视频的时候，在消息监听器onSuccess里面，监听到的消息body以下内容
thumbnailLocalPath
thumbnailRemotePath
remotePath
都为空

**Comment by dujiepeng** [comment]
@jb522185660 您好，已经做了修复，您可以试下。这个issue我先关闭，您有问题可以继续开新的。
