### ISSUE TITLE
iOS 获取某个不存在的会话时crash

### ISSUE THREAD

**Issue by MEnigma** [easemob/im_flutter_sdk#197]
EMChatManagerWrapper.m l:201~204

    NSString *conId = param[@"con_id"];
    EMConversationType type = [EMConversation typeFromInt:[param[@"type"] intValue]];
    BOOL needCreate = [param[@"createIfNeed"] boolValue];
    EMConversation *con = [EMClient.sharedClient.chatManager getConversation:conId
                                                                        type:type
                                                            createIfNotExist:needCreate];
    
当 dart层传入的con_id为null时,conid对象为NSNull

**Comment by dujiepeng** [comment]
@MEnigma 您可以加QQ群535134817
