### ISSUE TITLE
Flutter alpha版本的安卓推送功能的代码缺少

### ISSUE THREAD

**Issue by jb522185660** [easemob/im_flutter_sdk#206]
Flutter alpha版本的安卓推送功能的代码缺少
EMOptionsHelper的static EMOptions fromJson(JSONObject json) throws JSONException方法里面，应该加入类似
JSONObject pushConfig = json.getJSONObject("pushConfig");
EMPushConfig.Builder builder = new EMPushConfig.Builder(EMOptionsHelper.context);
boolean enableMiPush = pushConfig.getBoolean("enableMiPush");
if(enableMiPush == true) {
    String miAppId = pushConfig.getString("miAppId");
    String miAppKey = pushConfig.getString("miAppKey");
    builder.enableMiPush(miAppId, miAppKey);
}
boolean enableHWPush = pushConfig.getBoolean("enableHWPush");
if(enableHWPush == true) {
    builder.enableHWPush();
}
options.setPushConfig(builder.build());
这样子的启用推送代码
另外缺少了上传华为推送token的代码，应该在dart层添加通道调用java sdk的sendHMSPushTokenToServer方法去上传

**Comment by dujiepeng** [comment]
@jb522185660  已经添加这部分实现。

**Comment by jb522185660** [comment]
@dujiepeng sendHMSPushTokenToServer这个上传华为token到环信服务器的方法，还没有桥接
