### ISSUE TITLE
昨天的commit还没有加入sendHMSPushTokenToServer的方法

### ISSUE THREAD

**Issue by jb522185660** [easemob/im_flutter_sdk#208]
昨天的commit还没有加入sendHMSPushTokenToServer的方法

**Comment by wangxinjeff** [comment]
推送都是放在原生去集成的，sendHMSPushTokenToServer不需要去封装flutter的api的，你在原生获取到华为的推送token之后调用原生的sendHMSPushTokenToServer去上传就可以。流程就是flutter登录成功到主界面之后通过channel通知原生，原生这边再去注册华为推送获取推送token上传

**Comment by jb522185660** [comment]
获取华为推送token华为那边有个flutter的工具可以获取到，就是这一步《流程就是flutter登录成功到主界面之后通过channel通知原生》，这一步SDK可以实现吧？

**Comment by jb522185660** [comment]
在下面文件加入以下代码
em_sdk_method.dart
static const String sendHMSPushTokenToServer = 'sendHMSPushTokenToServer';
em_client.dart 
Future sendHMSPushTokenToServer(String token) async {
    if(token != null) {
      Map req = {'token': token};
      Map result = await _channel.invokeMethod(EMSDKMethod.sendHMSPushTokenToServer, req);
      EMError.hasErrorFromResult(result);
    }
    return;
  }
EMSDKMethod.java
static final String sendHMSPushTokenToServer = "sendHMSPushTokenToServer";
EMClientWrapper.java
if(EMSDKMethod.sendHMSPushTokenToServer.equals(call.method))
            {
                sendHMSPushTokenToServer(param, EMSDKMethod.sendHMSPushTokenToServer, result);
            }
private void sendHMSPushTokenToServer(JSONObject param, String channelName, Result result) throws JSONException {
        String token = param.getString("token");

        asyncRunnable(()->{
            EMClient.getInstance().sendHMSPushTokenToServer(token);
            onSuccess(result, channelName, true);
        });
    }

**Comment by jb522185660** [comment]
huawei_push: ^5.0.2+301可以直接使用flutter获取华为token,如果flutter sdk里面再增加sendHMSPushTokenToServer方法，就无须写安卓原生代码也可以上传华为token到服务器了

**Comment by dujiepeng** [comment]
@jb522185660 你说的这个是华为官方的库，如果官方都推荐这样使用，我们这边确实应该加上。不过华为这个操作感觉“比较奇怪”，从原生得到数据，再给原生，而且单独为华为提供一个这样的操作又感觉不通用，毕竟如果用小米，oppo之类手机的这个操作毫无意义，倒不如直接一个开关，然后原生那边控制获取和设置的时机，目前ios就是这样实现的。 @wangxinjeff  能实现我说的这样么？如果实现不了。就优先考虑华为官方的使用方式，提供一个channel来传token。

**Comment by jb522185660** [comment]
就提供一个channel传token就可以了

**Comment by dujiepeng** [comment]
@jb522185660 已经添加到alpha，会尽快同步到stable.
