### ISSUE TITLE
stable 版本demo iOS打包报错

### ISSUE THREAD

**Issue by AcYangle** [easemob/im_flutter_sdk#231]
![image](https://user-images.githubusercontent.com/15205440/107354826-98f4f480-6b09-11eb-921b-e9c1d6333265.png)

**Comment by dujiepeng** [comment]
环信ios3.7.4版本不支持armv7指令集，您打包时需要去掉该指令集。

**Comment by AcYangle** [comment]
已经解决了，我用的xcode12.4版本，配置项目ARCH的方式变了，整了好久

**Comment by AcYangle** [comment]
另外有个安卓华为离线推送的问题，新版本SDK怎么华为收不到离线推送了？

**Comment by dujiepeng** [comment]
@AcYangle 这个我来验证下，确定有问题的话我们来修复。
https://github.com/easemob/im_flutter_sdk/issues/234#issue-811698371
