### ISSUE TITLE
Android闪退

### ISSUE THREAD

**Issue by Xiaobai-1024** [easemob/im_flutter_sdk#241]
E/AndroidRuntime( 9278): java.lang.NullPointerException: Attempt to invoke virtual method 'long com.hyphenate.chat.EMMessage.getMsgTime()' on a null object reference
E/AndroidRuntime( 9278): 	at com.easemob.im_flutter_sdk.EMChatManagerWrapper.lambda$null$13(EMChatManagerWrapper.java:331)
E/AndroidRuntime( 9278): 	at com.easemob.im_flutter_sdk.-$$Lambda$EMChatManagerWrapper$itmNS2HI9oVhNdNvtMe9BBHxJls.compare(Unknown Source:4)
E/AndroidRuntime( 9278): 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
E/AndroidRuntime( 9278): 	at java.util.TimSort.sort(TimSort.java:220)
E/AndroidRuntime( 9278): 	at java.util.Arrays.sort(Arrays.java:1492)
E/AndroidRuntime( 9278): 	at java.util.ArrayList.sort(ArrayList.java:1470)
E/AndroidRuntime( 9278): 	at java.util.Collections.sort(Collections.java:206)
E/AndroidRuntime( 9278): 	at com.easemob.im_flutter_sdk.EMChatManagerWrapper.lambda$loadAllConversations$14$EMChatManagerWrapper(EMChatManagerWrapper.java:331)
E/AndroidRuntime( 9278): 	at com.easemob.im_flutter_sdk.-$$Lambda$EMChatManagerWrapper$cznuON-FwGpfxJ0233vRRVn7dYc.run(Unknown Source:6)
E/AndroidRuntime( 9278): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 9278): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 9278): 	at java.lang.Thread.run(Thread.java:919)

**Comment by dujiepeng** [comment]
@jonjon-coder 您是调用什么方法是出现的？

**Comment by Xiaobai-1024** [comment]
> @jonjon-coder 您是调用什么方法是出现的？

创建会话后，一个消息都不要发送，拉取会话列表就会。

**Comment by dujiepeng** [comment]
@jonjon-coder 在demo里测试了下没有复现，但是您这个crash确实是指向了排序的位置，我加了一个保护，您可以再试试。
