### ISSUE TITLE
小米手机可接受到推送消息，但是 消息代理函数 不执行，（已实现 EMConnectionListener 并注册监听）

### ISSUE THREAD

**Issue by lovecrossyou** [easemob/im_flutter_sdk#243]
小米手机可接受消息，但是 消息代理函数 不执行

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp>
    implements EMChatManagerListener, EMConnectionListener {
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  final BehaviorSubject<ReceivedNotification>
      didReceiveLocalNotificationSubject =
      BehaviorSubject<ReceivedNotification>();

  final BehaviorSubject<String> selectNotificationSubject =
      BehaviorSubject<String>();

  @override
  void initState() {
    super.initState();
    registeListeners();
    initLocalNitifications();
  }

  void registeListeners() {
    EMClient.getInstance.addConnectionListener(this);
    EMClient.getInstance.chatManager.addListener(this);
  }

  void unRegisteListeners() {
    // 移除连接监听
    EMClient.getInstance.removeConnectionListener(this);
    EMClient.getInstance.chatManager.removeListener(this);
  }

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: Size(750, 1334),
      allowFontScaling: false,
      builder: () => GetMaterialApp(
        initialRoute: '/index',
        // initialRoute: '/account_security',
        navigatorKey: G.navigatorKey,
        getPages: RouteConfig.getPages,
        debugShowCheckedModeBanner: false,
        title: '联合科创',
        theme: KCHTheme.lightTheme,
        // darkTheme: KCHTheme.darkTheme,
        locale: Locale('zh', 'CN'), // 将会按照此处指定的语言翻译
        fallbackLocale: Locale('en', 'US'),
        builder: EasyLoading.init(),
      ),
    );
  }

  @override
  void onConnected() {
    print('环信 已连接');
  }

  @override
  void onDisconnected(int errorCode) {}

  @override
  onCmdMessagesReceived(List<EMMessage> messages) {
    print("onCmdMessagesReceived#################阿达###############");
    throw UnimplementedError();
  }

  @override
  onConversationsUpdate() {
    throw UnimplementedError();
  }

  @override
  onMessagesDelivered(List<EMMessage> messages) {
    print("onMessagesDelivered################################");
    throw UnimplementedError();
  }

  @override
  onMessagesRead(List<EMMessage> messages) {
    print("onMessagesRead################################");
    throw UnimplementedError();
  }

  @override
  onMessagesRecalled(List<EMMessage> messages) {
    throw UnimplementedError();
  }

  @override
  onMessagesReceived(List<EMMessage> messages) {
    EMMessage lastMessage = messages.first;
    String from = lastMessage.from;
    String content = lastMessage.body.toJson()['content'];
    _showNotification(from, content);
  }

  Future<void> _showNotification(
      [String from = "联合科创", String content = "消息"]) async {
    var androidPlatformChannelSpecifics = AndroidNotification
Details(
        channelId, '${channelId}name', 'your channel description',
        importance: Importance.Max, priority: Priority.High, ticker: 'ticker');
    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
        10, '来自$from 的消息', '$content', platformChannelSpecifics,
        payload: 'item x');
  }

  void initLocalNitifications() async {
    var initializationSettingsAndroid =
        AndroidInitializationSettings('app_icon');
    var initializationSettingsIOS = IOSInitializationSettings(
        onDidReceiveLocalNotification:
            (int id, String title, String body, String payload) async {
      didReceiveLocalNotificationSubject.add(ReceivedNotification(
          id: id, title: title, body: body, payload: payload));
    });
    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    await flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: (String payload) async {
      if (payload != null) {
        debugPrint('notification payload: ' + payload);
        //  点击消息后，跳转到 消息列表
        // G.pushNamed("/messages");
        G.goTab(2);
      }
      selectNotificationSubject.add(payload);
    });
  }

  @override
  onConversationRead(String from, String to) {
    throw UnimplementedError();
  }

  @override
  void dispose() {
    unRegisteListeners();
    super.dispose();
  }

}

**Comment by lovecrossyou** [comment]
sdk  存在问题 ，改为 下面的就好了，😄


![image](https://user-images.githubusercontent.com/6503767/111139323-f6260f00-85bb-11eb-8a7a-d5c4e495c5e6.png)

**Comment by dujiepeng** [comment]
@lovecrossyou 感谢支持，调用EMChatManager时需要使用 `EMClient.getInstance.chatManager`
