### ISSUE TITLE
ios 发送gif被压缩成静态图片

### ISSUE THREAD

**Issue by AcYangle** [easemob/im_flutter_sdk#251]
iOS发送或接收的GIF图都会被压缩成静态图片，安卓正常，但安卓向iOS发送的GIF，iOS端展示的也是静态图，
调试发现，iOS下载GIF存入本地时，存入的就是静态图，安卓无此问题
另外，demo中发送图片的方式，如果选择的是GIF，会出现反复收到监听回调，导致发送图片刷屏的问题

**Comment by dujiepeng** [comment]
@AcYangle  目前iOS中有图片压缩，这会导致git变成了jpeg，目前官方的方案是使用fileBody发送，后期会协调native中增加gif类型Body，彻底解决该问题，请持续关注！thx.

**Comment by dujiepeng** [comment]
@AcYangle 您可以加QQ群535134817
