### ISSUE TITLE
更新到最新代码后消息发送异常

### ISSUE THREAD

**Issue by 01098996** [easemob/im_flutter_sdk#265]
更新前的git commit SHA:  8129d89b4f5cf0045efbff50c5a7b567105b6e30
更新后的git commit SHA:  fe3e6ae09c7d37af25c3ac60a882747ce45e6065

更新后所有返回的消息id均为null

log:
D/ONE SDK (18309): [2021/03/29 14:05:40:203]: Msg already exists in this conversation, do not insert again. msg id: null

**Comment by dujiepeng** [comment]
@01098996 今天有一次修改，可以重新拉取下stable 分支。感谢支持。
