### ISSUE TITLE
更新到最新代码后消息发送异常

### ISSUE THREAD

**Issue by 01098996** [easemob/im_flutter_sdk#270]
#265 修改后出现新bug，发送消息后没有发送成功回调。重新进入会话页面查询刚发送的消息，消息状态是正常的。

**Comment by dujiepeng** [comment]
@01098996 发消息需要实现EMMessageStatusListener接口，监听消息结束回调。
```msg.setMessageListener(this);```
```
abstract class EMMessageStatusListener {
  /// 消息进度
  void onProgress(int progress) {}

  /// 消息发送失败
  void onError(EMError error) {}

  /// 消息发送成功
  void onSuccess() {}

  /// 消息已读
  void onReadAck() {}

  /// 消息已送达
  void onDeliveryAck() {}

  /// 消息状态发生改变
  void onStatusChanged() {}
}```

**Comment by 01098996** [comment]
@dujiepeng 实现了这些接口， easemob/im_flutter_sdk@c5571b8ac5cc29571b782f37925ba308deea671e 是可以正常收到回调， easemob/im_flutter_sdk@f3a915bb22ef8a55e4342c45793323756400a519 就收不到。

**Comment by dujiepeng** [comment]
@01098996 我测试了下demo，表现正常，没出现问题，您能提供下您这部分的代码么？

**Comment by 01098996** [comment]
@dujiepeng  有几个不一样的地方：
1.demo是单聊，我这边的场景是群聊。
2.demo只判断了PROGRESS和FAIL的状态，其它状态均为已发送。实际上CREATE状态并不是已发送状态。

**Comment by dujiepeng** [comment]
@01098996 好，我试下。

**Comment by dujiepeng** [comment]
@01098996 resend有问题，正常send的时候正常，目前已经修复，可以在alpha分支试下。
