### ISSUE TITLE
发送消息收不到通知

### ISSUE THREAD

**Issue by 01098996** [easemob/im_flutter_sdk#272]
#270 修改后变成概率性出现，10次有6~7次收不到发送成功回调

**Comment by dujiepeng** [comment]
@01098996 目前怀疑是ui的问题，在demo上出现了，多次快速调用setState的时候，再刷新前，消息就已经发送成功并且回调了。可以打断点或者输出下是否有发送成功的回调。

**Comment by 01098996** [comment]
@dujiepeng  没有出现bug的会有通知，反之则没有

**Comment by dujiepeng** [comment]
@01098996 没太懂您这个描述。

**Comment by dujiepeng** [comment]
@01098996 您可以加QQ群535134817
