### ISSUE TITLE
数据字段名错误

### ISSUE THREAD

**Issue by amorwilliams** [easemob/im_flutter_sdk#282]
https://github.com/easemob/im_flutter_sdk/blob/d413d622b01298440d75f1f6278f0305e89385ae/android/src/main/java/com/easemob/im_flutter_sdk/EMHelper.java#L154
https://github.com/easemob/im_flutter_sdk/blob/d413d622b01298440d75f1f6278f0305e89385ae/android/src/main/java/com/easemob/im_flutter_sdk/EMHelper.java#L290
https://github.com/easemob/im_flutter_sdk/blob/d413d622b01298440d75f1f6278f0305e89385ae/lib/src/models/em_chat_room.dart#L27
https://github.com/easemob/im_flutter_sdk/blob/d413d622b01298440d75f1f6278f0305e89385ae/lib/src/models/em_group.dart#L67

**Comment by dujiepeng** [comment]
@amorwilliams  thx!

**Comment by dujiepeng** [comment]
@amorwilliams 欢迎您加群535134817 。
