### ISSUE TITLE
im_flutter_sdk stable分支 消息状态监听 

### ISSUE THREAD

**Issue by SuLuopital** [easemob/im_flutter_sdk#284]
在widget中添加消息状态监听EMMessageStatusListener，，init时setMessageListener，但直到消息发送成功之后也没有触发相应的回调

**Comment by dujiepeng** [comment]
@SuLuopital  目前demo测试正常，不确定是不是目前的写法上有没考虑到的地方，暂定为调用方式不对，可以加群535134817进一步沟通调调用方式和这部分的实现。
