### ISSUE TITLE
字段不匹配

### ISSUE THREAD

**Issue by amorwilliams** [easemob/im_flutter_sdk#288]
https://github.com/easemob/im_flutter_sdk/blob/74bd011f018d15825f7b967733e842bfb6cacf73/android/src/main/java/com/easemob/im_flutter_sdk/EMHelper.java#L706
https://github.com/easemob/im_flutter_sdk/blob/74bd011f018d15825f7b967733e842bfb6cacf73/lib/src/models/em_message.dart#L643-L644

**Comment by amorwilliams** [comment]
https://github.com/easemob/im_flutter_sdk/blob/74bd011f018d15825f7b967733e842bfb6cacf73/android/src/main/java/com/easemob/im_flutter_sdk/EMHelper.java#L700-L716
https://github.com/easemob/im_flutter_sdk/blob/74bd011f018d15825f7b967733e842bfb6cacf73/ios/Classes/EMMessage%2BFlutter.m#L456-L472
Is there missing `thumbnailStatus` field in `imageBodyToJson` method from `EMHelper.java`  ?

**Comment by dujiepeng** [comment]
@amorwilliams 这个是目前原生那边没有暴露出来，flutter等下次安卓发版才能提供这个属性。
