### ISSUE TITLE
如何同时集成客服云sdk

### ISSUE THREAD

**Issue by good-good-study** [easemob/im_flutter_sdk#292]
Flutter 端集成了 环信Flutter sdk ，以下是集成方式 ：
dependencies:
  im_flutter_sdk:  
    git:  
      url: https://github.com/easemob/im_flutter_sdk.git 
      ref: stabl
如何同时集成客服云sdk

**Comment by good-good-study** [comment]
目前flutter集成了im, android集成了kefu sdk ， 但是编译时会产生依赖冲突

**Comment by dujiepeng** [comment]
@good-good-study 目前flutter 和客服没有办法一起使用，后续应该也没有这个计划。
