### ISSUE TITLE
撤回消息需要撤回两次才成功

### ISSUE THREAD

**Issue by ixre** [easemob/im_flutter_sdk#293]
１.　当撤销后,　消息还存在.　重新进入会话聊天.　消息也还是存在的.
２.　再次撤销,　消息消失,　重新进入聊天.　消息也不在了.　对方的聊天框消息也被撤回.　

当尝试使用SDK和RESTAPI结合,　在一次调用中请求两次撤销.　
仍然还是需要再操作一次.

**Comment by dujiepeng** [comment]
@ixre 这个感觉是因为消息发送的时候没有更新消息id导致的，可以加群535134817具体描述下情况。
