### ISSUE TITLE
Vivo配置推送不成功，com.vivo.push.app_id expected Integer but value was a java.lang.String

### ISSUE THREAD

**Issue by elricym** [easemob/im_flutter_sdk#300]
按照教程配置的Vivo推送，也对照了Vivo官网上的教程，不能把app_id cast成int是什么原因？

W/Bundle  (30480): Key com.vivo.push.app_id expected Integer but value was a java.lang.String.  The default value 0 was returned.
W/Bundle  (30480): Attempt to cast generated internal exception:
W/Bundle  (30480): java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
W/Bundle  (30480): 	at android.os.BaseBundle.getInt(BaseBundle.java:1052)
W/Bundle  (30480): 	at android.os.BaseBundle.getInt(BaseBundle.java:1034)
W/Bundle  (30480): 	at com.hyphenate.push.EMPushConfig$Builder.enableVivoPush(Unknown Source:27)
W/Bundle  (30480): 	at com.easemob.im_flutter_sdk.EMOptionsHelper.fromJson(EMHelper.java:92)
W/Bundle  (30480): 	at com.easemob.im_flutter_sdk.EMClientWrapper.init(EMClientWrapper.java:231)
W/Bundle  (30480): 	at com.easemob.im_flutter_sdk.EMClientWrapper.onMethodCall(EMClientWrapper.java:38)
W/Bundle  (30480): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/Bundle  (30480): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/Bundle  (30480): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/Bundle  (30480): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/Bundle  (30480): 	at android.os.MessageQueue.next(MessageQueue.java:339)
W/Bundle  (30480): 	at android.os.Looper.loop(Looper.java:188)
W/Bundle  (30480): 	at android.app.ActivityThread.main(ActivityThread.java:7172)
W/Bundle  (30480): 	at java.lang.reflect.Method.invoke(Native Method)
W/Bundle  (30480): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
W/Bundle  (30480): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by dujiepeng** [comment]
这个是因为参数写在了build.gradle的原因，这个可以加群535134817，沟通具体解决方式。
