### ISSUE TITLE
Pending exception java.lang.ClassNotFoundException: Didn't find class "com.hyphenate.chat.adapter.EMAREncryptUtils" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar"

### ISSUE THREAD

**Issue by hchen1987** [easemob/im_flutter_sdk#301]
release报这个错，debug木问题，请教一下是什么问题导致的？

**Comment by and2long** [comment]
安卓需要自己配置一下混淆规则才行。

**Comment by hchen1987** [comment]
请问有参考的例子吗？

**Comment by and2long** [comment]
[http://docs-im.easemob.com/im/android/sdk/import#app_%E6%89%93%E5%8C%85%E6%B7%B7%E6%B7%86](http://docs-im.easemob.com/im/android/sdk/import#app_%E6%89%93%E5%8C%85%E6%B7%B7%E6%B7%86)

**Comment by hchen1987** [comment]
收到，我尝试一下，多谢。
