### ISSUE TITLE
【发送视频消息】日志显示发送成功，但是界面上没有显示出来视频消息。

### ISSUE THREAD

**Issue by and2long** [easemob/im_flutter_sdk#302]
flutter: EaseMob | V | 发送成功 -- {from: 17782576644, to: 13909251579, body: {type: video, secret: YWrrEKMgEeuT5s3XJecJ0eMao6pvPp_YGQkl4LFo0uiIHnCX, remotePath: https://a1-v2.easemob.com/1123210406152002/demo/chatfiles/616a9cf0-a320-11eb-bfbb-d1e41027ff78, fileSize: 2170106, localPath: /private/var/mobile/Containers/Data/Application/1D59AB6C-DD14-42D7-94C1-12C237B5ECDB/tmp/trim.8EEC4405-52EE-42A1-8D87-77FBDCB3A19D.MOV, displayName: , fileStatus: 1, duration: 0, thumbnailLocalPath: , thumbnailRemotePath: , thumbnailSecret: null, height: 100.0, width: 100.0, thumbnailStatus: 1}, attributes: {}, direction: send, hasRead: true, hasReadAck: false, hasDeliverAck: false, msgId: 865434636195469456, conversationId: 13909251579, chatType: 0, localTime: 1619064501884, serverTime: 1619064501884, status: 2}

![image](https://user-images.githubusercontent.com/17178272/115679515-40519b80-a385-11eb-851c-6b40c691aadd.png)

图中，最后两条消息是发送出去的视频消息，界面上无法显示出来。

**Comment by dujiepeng** [comment]
@and2long demo上没有添加视频消息的bubble。

**Comment by and2long** [comment]
> @and2long demo上没有添加视频消息的bubble。

你的意思是说 不支持视频消息吗？

SDK 里是有发送视频消息的API的。

**Comment by and2long** [comment]
demo 消息列表中的视频消息预览没有实现。
