### ISSUE TITLE
iOS虚拟机发送录音文件找不到

### ISSUE THREAD

**Issue by hwh97** [easemob/im_flutter_sdk#303]
发送的文件路径/Users/***/Library/Developer/CoreSimulator/Devices/50094F55-0992-476B-A07B-D448C7F23AD7/data/Containers/Data/Application/C760F36E-DB28-41EA-91FB-424D14531C5D/Documents/voice/1619334452204990.aac

错误：
flutter: EaseMob | V | 发送失败 -- {error: {description: /Users/\*\*/Library/Developer/CoreSimulator/Devices/50094F55-0992-476B-A07B-D448C7F23AD7/data/Containers/Data/Application/C760F36E-DB28-41EA-91FB-424D14531C5D/Library/Developer/CoreSimulator/Devices/50094F55-0992-476B-A07B-D448C7F23AD7/data/Containers/Data/Application/C760F36E-DB28-41EA-91FB-424D14531C5D/Documents/voice/1619334452204990.aac not exist, code: 401}, localTime: 1619334454155, message: {hasRead: true, direction: send, localTime: 1619334454155, body: {secret: , fileStatus: 1, displayName: , localPath: /Users/\*\*/Library/Developer/CoreSimulator/Devices/50094F55-0992-476B-A07B-D448C7F23AD7/data/Containers/Data/Application/C760F36E-DB28-41EA-91FB-424D14531C5D/Library/Developer/CoreSimulator/Devices/50094F55-0992-476B-A07B-D448C7F23AD7/data/Containers/Data/Application/C760F36E-DB28-41EA-91FB-424D14531C5D/Documents/voice/1619334452204990.aac, duration: 1, remotePath: , type: voice, fileSize: 24956}, conversationId: 133607<…>

路径好像被修改了，跟传入的值不一致。

**Comment by dujiepeng** [comment]
@hwh97 这个需要等原生sdk升级，那边有一个路径的处理没有考虑模拟器的情况。

**Comment by dujiepeng** [comment]
也可以加群535134817 沟通。
