### ISSUE TITLE
获取聊天室人员详情报错

### ISSUE THREAD

**Issue by oneQiu** [easemob/im_flutter_sdk#324]
1. 我在客户端获取聊天室人员详情的时候报错
![image](https://user-images.githubusercontent.com/50658231/119380049-cd747100-bcf2-11eb-864e-0e6fa9102037.png)
![image](https://user-images.githubusercontent.com/50658231/119379996-bc2b6480-bcf2-11eb-9d75-5a69fa092411.png)

2. 我发送消息的时候发送的是一条，但是另外一个设备接收到的是多个重复消息，打印日志也是发送的是一条，重复接收了多个消息。
![image](https://user-images.githubusercontent.com/50658231/119380474-5ab7c580-bcf3-11eb-80b1-b8980cfbba74.png)

**Comment by dujiepeng** [comment]
@oneQiu 第一个应该是sdk返回的状态不对，这个可以sdk处理，第二个应该不是sdk的问题，需要您看下ui实现上有什么问题。

**Comment by oneQiu** [comment]
@dujiepeng 一个新问题，自定义消息。传递params 会报错，因为传递类型是,Map<dynamic, dynamic>'  内部方法却是Map<String, String>。
![image](https://user-images.githubusercontent.com/50658231/121018501-19361880-c7d1-11eb-8b96-340104e12938.png)
![image](https://user-images.githubusercontent.com/50658231/121017403-d0ca2b00-c7cf-11eb-9587-a4f90e4e5e04.png)
![image](https://user-images.githubusercontent.com/50658231/121018447-07547580-c7d1-11eb-9ba0-d7c315b9bfe9.png)
![image](https://user-images.githubusercontent.com/50658231/121018460-0ae7fc80-c7d1-11eb-8147-602983361f4e.png)

**Comment by dujiepeng** [comment]
您可以进群535134817
