### ISSUE TITLE
获取指定id的用户的用户属性方法使用报错，flutter版本2.0.6

### ISSUE THREAD

**Issue by YaoHoHo** [easemob/im_flutter_sdk#326]
![7537B109-F050-4ACB-A69F-678B9EA13BCA](https://user-images.githubusercontent.com/20201118/120273131-ad3f4600-c2e0-11eb-9580-8bac5349e9e0.png)

**Comment by YaoHoHo** [comment]
还有一个问题，当更新用户属性的时候，头像链接地址好像会被截取。
![123](https://user-images.githubusercontent.com/20201118/120276615-820b2580-c2e5-11eb-888b-c59933b631fa.png)

**Comment by jinliang04551** [comment]
你好 ：
1.更新用户属性的问题 可以发一下你的调用的代码吗  还有你打断点的代码的完整截图可以提供下吗 
2.图片我用第三方的试了一下 没有问题    附截图   如还有问题 
![QQ20210607-161506fetch](https://user-images.githubusercontent.com/3039130/120983068-efb6c600-c7ab-11eb-9d4c-7f28ce2432d3.png)
![QQ20210607-161427update](https://user-images.githubusercontent.com/3039130/120983090-f47b7a00-c7ab-11eb-8d2d-073cff450938.png)

可以把具体的逻辑截图一下

**Comment by dujiepeng** [comment]
@jinliang04551 @YaoHoHo

**Comment by YaoHoHo** [comment]
![1](https://user-images.githubusercontent.com/20201118/120993379-0cf09200-c7b6-11eb-9437-f2c5a58066cf.png)
![2](https://user-images.githubusercontent.com/20201118/120993006-b8e5ad80-c7b5-11eb-8a88-e7fc48c6098a.png)
可以试下我这个地址  http://thirdqq.qlogo.cn/g?b=oidb&k=F3O4ZsbrmMjAwJRyAhmkaw&s=100&t=1556336302 ，这是qq登录返回的头像地址
上面两张截图是原生android的断点，存取用户属性的时候，地址是完整的，但是回调的返回结果中图像地址被截取了。
![3](https://user-images.githubusercontent.com/20201118/120995487-0531ed00-c7b8-11eb-97bd-19fa2bdeafb0.png)
![4](https://user-images.githubusercontent.com/20201118/120995849-635ed000-c7b8-11eb-9c41-54236e0cabbc.png)
这两张是flutter断点截图

**Comment by jinliang04551** [comment]
麻烦把第一个获取用户属性的代码的完整截图发一下吧   @YaoHoHo

**Comment by YaoHoHo** [comment]
![3](https://user-images.githubusercontent.com/20201118/121018216-c52b3400-c7d0-11eb-9c73-431b2560bd11.png)
![2](https://user-images.githubusercontent.com/20201118/121018215-c52b3400-c7d0-11eb-8a02-b2d6e66fdd88.png)
第一张是使用api的截图和传入的数据，第二张是报错，我自己改成forEach的写法没有问题，用的sdk是2.0.6

**Comment by jinliang04551** [comment]
> ![3](https://user-images.githubusercontent.com/20201118/121018216-c52b3400-c7d0-11eb-9c73-431b2560bd11.png)
> ![2](https://user-images.githubusercontent.com/20201118/121018215-c52b3400-c7d0-11eb-8a02-b2d6e66fdd88.png)
> 第一张是使用api的截图和传入的数据，第二张是报错，我自己改成forEach的写法没有问题，用的sdk是2.0.6


嗯 第二个图片保存已经找到问题了  第一个获取用户属性的 你那边看到的是这样的吗 
![QQ20210607-210107userinfo](https://user-images.githubusercontent.com/3039130/121021381-e80b1780-c7d3-11eb-86b6-95bbf0149d8f.png)

**Comment by jinliang04551** [comment]
@YaoHoHo

**Comment by YaoHoHo** [comment]
噢，我这边的版本少了 .toList(); 那应该是这个写法问题。

**Comment by jinliang04551** [comment]
> 噢，我这边的版本少了 .toList(); 那应该是这个写法问题。

嗯 好的 应该是我们少合并了 后面会一起处理的 感谢指正

**Comment by jinliang04551** [comment]
@YaoHoHo  我看我们这边的代码里是有toList() 的 你再重新拉取一下吧

**Comment by YaoHoHo** [comment]
恩恩
