### ISSUE TITLE
stable分支准备什么时候支持flutter2.0

### ISSUE THREAD

**Issue by hibiao** [easemob/im_flutter_sdk#330]
stable分支准备什么时候支持flutter2.0

**Comment by dujiepeng** [comment]
@hibiao 您好，因为目前ui库没有全部适配空安全，导致demo无法运行，暂时还没有办法发2.0的stable，您可以用flutter2.0_dev分支，如果遇到问题可以随时反馈。

**Comment by dujiepeng** [comment]
您好，预计10月左右会放出。
