### ISSUE TITLE
【视频消息】提示文件过大发送失败。视频文件大小支持多大？

### ISSUE THREAD

**Issue by and2long** [easemob/im_flutter_sdk#332]
` EaseMob | V | 发送失败 -- {localTime: 1623060659808, code: 405, description: File too large, message: {conversationId: 19935964171, msgId: 162306065980823340, hasDeliverAck: false, body: {remotePath: , displayName: , secret: , type: video, thumbnailSecret: , duration: 0, fileSize: 0, fileStatus: 3, thumbnailRemotePath: , localPath: /data/user/0/com.qunai.doctor/cache/image_picker7123699892530490805.mp4, width: 100, thumbnailLocalPath: null, height: 100}, hasReadAck: false, localTime: 1623060659808, hasRead: true, from: 19935964171, serverTime: 1623060659818, to: 19935964171, status: 3, chatType: 0, direction: send}}`

**Comment by dujiepeng** [comment]
@and2long 应该是限制在10MB以下，这个是由服务器限制的。可以联系您对应的商务或者通过工单处理。
