### ISSUE TITLE
fatal error: 'AgoraRtcKit/AgoraRtcEngineKit.h' file not found     #import <AgoraRtcKit/AgoraRtcEngineKit.h>

### ISSUE THREAD

**Issue by jason-ivy** [easemob/im_flutter_sdk#338]
![image](https://user-images.githubusercontent.com/8363595/121818420-ab4e8d00-ccb9-11eb-972f-e76b739a1101.png)

**Comment by jason-ivy** [comment]
没人能回复吗

**Comment by dujiepeng** [comment]
@jason-ivy  这个报错看起来是用的ios10以下的版本么？ unauthorizationoptionbade 这个应该是10以上才支持的。
