### ISSUE TITLE
使用同意入群申请，拒绝入群申请的方法时，提示群组不存在

### ISSUE THREAD

**Issue by YaoHoHo** [easemob/im_flutter_sdk#350]
![1](https://user-images.githubusercontent.com/20201118/124060083-dc231600-da5e-11eb-817f-016a0109716b.png)
![2](https://user-images.githubusercontent.com/20201118/124060099-e218f700-da5e-11eb-841f-f593aa2cee45.png)
原生调用中groupId 和 username 参数传递反了

**Comment by dujiepeng** [comment]
@YaoHoHo  Thx!
