### ISSUE TITLE
什么时候能支持Flutter2.0 的 Null-Safety

### ISSUE THREAD

**Issue by good-good-study** [easemob/im_flutter_sdk#355]
什么时候能支持Flutter2.0 的 Null-Safety

**Comment by dujiepeng** [comment]
@good-good-study 目前sdk有2.0的branch，还没有把demo都升级到null safety, 您可以先用2.0的分支，调试开发，如果遇到问题提交issue即可。

**Comment by good-good-study** [comment]
哦哦，现在已经用了这个2.0的flutter2_dev分支了，但是现在调用了加载所有会话的方法后，一直报错，app重装也是一样的错误。

![截屏2021-07-06 上午10 15 39](https://user-images.githubusercontent.com/20188392/124532855-ec166d80-de43-11eb-95f4-4d89b394a3dd.png)
