### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by tzt1994** [easemob/im_flutter_sdk#356]
flutter2_dev分支

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'
E/flutter ( 1208): #0      new EMConversation.fromJson (package:im_flutter_sdk/src/models/em_conversation.dart:35:54)
E/flutter ( 1208): #1      EMChatManager.loadAllConversations.<anonymous closure> (package:im_flutter_sdk/src/em_chat_manager.dart:160:43)
E/flutter ( 1208): #2      List.forEach (dart:core-patch/growable_array.dart:403:8)
E/flutter ( 1208): #3      EMChatManager.loadAllConversations (package:im_flutter_sdk/src/em_chat_manager.dart:159:47)
E/flutter ( 1208): <asynchronous suspension>
E/flutter ( 1208): #4      MessageState.initData (package:video_pk/pages/message/message.dart:86:38)
E/flutter ( 1208): <asynchronous suspension>

![image](https://user-images.githubusercontent.com/15625580/124690625-11bb7980-df0d-11eb-8cf7-ebf69d7fd422.png)

EMMessage.fromJson(Map)要求传入为Map，不可空。
map['lastReceivedMessage']的值可能为空，所以这里报错了
往尽快修复

**Comment by vance-liu** [comment]
同样的问题，希望尽快修复

**Comment by dujiepeng** [comment]
已修复。
