### ISSUE TITLE
2.0版本-EMMessage的消息监听无法取消 

### ISSUE THREAD

**Issue by randomjoho** [easemob/im_flutter_sdk#357]
我没办法传null进来移除消息监听. 
void setMessageListener(EMMessageStatusListener  listener) {
    this.listener = listener;
    if (listener != null) {
      MessageCallBackManager.getInstance.addMessage(this);
    } else {
      MessageCallBackManager.getInstance.removeMessage(this);
    }
  }
@dujiepeng

**Comment by randomjoho** [comment]
EMConversation 

factory EMConversation.fromJson(Map<String, dynamic> map) {
    Map<String, String>? ext = map['ext'];
    String? name;
    if (ext != null) {
      name = ext['con_name'];
      ext.remove('con_name');
    }
    

    return EMConversation._private()
      ..type = typeFromInt(map['type'])
      ..id = map['con_id']
      .._unreadCount = map['unreadCount']
      .._ext = ext
      .._name = name ?? ''
      .._latestMessage = EMMessage.fromJson(map['latestMessage'])
      .._lastReceivedMessage = EMMessage.fromJson(map['lastReceivedMessage']);
  }

map里 latestMessage或者lastReceivedMessage 为空会导致无法获取EMConversation对象

**Comment by alexwuchao** [comment]
的确是这样，不知道他们什么时候修复

**Comment by dujiepeng** [comment]
已修复。
