### ISSUE TITLE
Flutter2_dev分支, ，获取会话失败

### ISSUE THREAD

**Issue by good-good-study** [easemob/im_flutter_sdk#359]
哦哦，现在已经用了这个2.0的flutter2_dev分支了，但是现在调用了加载所有会话的方法后，一直报错，app重装也是一样的错误。

![截屏2021-07-06 上午10 15 39](https://user-images.githubusercontent.com/20188392/124532855-ec166d80-de43-11eb-95f4-4d89b394a3dd.png)

**Comment by good-good-study** [comment]
@dujiepeng 你好，这个问题有修复吗？

**Comment by dujiepeng** [comment]
已修复。
