### ISSUE TITLE
自定义属性，ios和android 消息数据类型不一致

### ISSUE THREAD

**Issue by good-good-study** [easemob/im_flutter_sdk#367]
使用的版本是 ： flutter2_dev
扩展属性时，attributes中自定义的key对应的value，如果value是非基本数据类型的话，例如，value为一个对象，在ios端，接收到的消息结构是一个对象， 但是在android端，却是一个字符串。

如下图，android、ios收到的消息对比：
<img width="821" alt="Android" src="https://user-images.githubusercontent.com/20188392/126595540-0370a9e5-854e-464c-827f-019a3bf87ce7.png">
<img width="819" alt="ios" src="https://user-images.githubusercontent.com/20188392/126595552-990e769d-14d5-4fd7-bc89-82f9f54645cc.png">

**Comment by dujiepeng** [comment]
已修复。
