### ISSUE TITLE
ios设备 onMessagesReceived 回调了两次

### ISSUE THREAD

**Issue by good-good-study** [easemob/im_flutter_sdk#369]
首先在测试环信收发消息的过程中，发现在android设备上显示正常（android设备之间收发消息均正常），在ios设备上测试发现，同一条消息 onMessagesReceived 回调了两次，并且这两个消息的 msgId是一样的，消息时间也是一样的，但是 打印过程中发现 EMMessage 的 hashCode值不一样， 导致消息重复加载。

以下是注册消息监听的做法：

![截屏2021-07-27 上午11 11 19](https://user-images.githubusercontent.com/20188392/127089409-484d812c-7867-451d-a40b-25f84a4c4623.png)

![截屏2021-07-27 上午11 11 03](https://user-images.githubusercontent.com/20188392/127089419-68f5651a-8899-4a64-96bf-864ec2c49734.png)

此时从其他设备发送一条文本消息后（文本内容为@@abc），ios设备 收到消息后的 日志打印如下：

第一次回调：

DEBUG - onMessagesReceived: msgId - 901038570439968896 , hashCode - 905870074
DEBUG - onMessagesReceived: [{"from":"609604647c7cf4","to":"149028080779265","body":{"type":"txt","content":"@@abc"},"attributes":{"alias":"User 4","avatar":"http://tuiqiu_circle.vaiwan.com/avatar/zhaozilong.jpg","code":"4"},"direction":"rec","hasRead":false,"hasReadAck":false,"hasDeliverAck":false,"msgId":"901038570439968896","conversationId":"149028080779265","chatType":1,"localTime":1627354190102,"serverTime":1627354190320,"status":2}]

第二次回调：

[推球] DEBUG - onMessagesReceived: msgId - 901038570439968896 , hashCode - 466507261
[推球] DEBUG - onMessagesReceived: [{"from":"609604647c7cf4","to":"149028080779265","body":{"type":"txt","content":"@@abc"},"attributes":{"alias":"User 4","avatar":"http://tuiqiu_circle.vaiwan.com/avatar/zhaozilong.jpg","code":"4"},"direction":"rec","hasRead":false,"hasReadAck":false,"hasDeliverAck":false,"msgId":"901038570439968896","conversationId":"149028080779265","chatType":1,"localTime":1627354190102,"serverTime":1627354190320,"status":2}]

**Comment by dujiepeng** [comment]
@good-good-study 这个是必现的么。

**Comment by good-good-study** [comment]
@dujiepeng 是的

**Comment by zmm2tysu** [comment]
我也出现了=。=
我有一台设备用模拟器出现两次回调。
我两台设备都用真机后就没这个问题了

**Comment by good-good-study** [comment]
@dujiepeng 大佬，这个问题有结果了吗😂

**Comment by zmm2tysu** [comment]
> @dujiepeng 大佬，这个问题有结果了吗😂

你看你是不是有个用的模拟器？

**Comment by good-good-study** [comment]
> > @dujiepeng 大佬，这个问题有结果了吗😂
> 
> 你看你是不是有个用的模拟器？

对

**Comment by dujiepeng** [comment]
@good-good-study 加群535134817。
