### ISSUE TITLE
这个插件跟极光推送冲突了？

### ISSUE THREAD

**Issue by zmm2tysu** [easemob/im_flutter_sdk#373]
我同时接入了这个im和极光推送，现在发现生产环境的包无法收到极光推送，只有屏蔽了这个插件才能收到推送？请问该怎么改才能同时使用两个插件？

**Comment by dujiepeng** [comment]
您好，因为极光和环信的sdk都直接把注册deviceToken的方式写在了插件里，这样可能会导致一方无法收到回调，环信sdk也提供了单独设置deviceToken的api在PushManager中，您可以主动设置。
