### ISSUE TITLE
demo不能点对点聊天吗

### ISSUE THREAD

**Issue by tongdong** [easemob/im_flutter_sdk#374]
D/EMChatManager( 3349): convID:156062689853441
E/flutter ( 3349): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 3349): Receiver: null
E/flutter ( 3349): Tried calling: []("to")
E/flutter ( 3349): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 3349): #1      new EMMessage.fromJson (package:im_flutter_sdk/src/models/em_message.dart:357:17)
E/flutter ( 3349): #2      new EMConversation.fromJson (package:im_flutter_sdk/src/models/em_conversation.dart:34:36)
E/flutter ( 3349): #3      EMChatManager.getConversation (package:im_flutter_sdk/src/em_chat_manager.dart:101:28)
E/flutter ( 3349): <asynchronous suspension>
E/flutter ( 3349): #4      JoinedGroupsPageState._chat (package:easeim_flutter_demo/pages/group/joined_groups_page.dart:268:26)
E/flutter ( 3349): <asynchronous suspension>
E/flutter ( 3349):

**Comment by dujiepeng** [comment]
您好，您使用的是哪个分支？也可以加群535134817
