### ISSUE TITLE
java.lang.NumberFormatException: For input string: "mserver"

### ISSUE THREAD

**Issue by xiayanping** [easemob/im_flutter_sdk#408]
im_flutter_sdk:
    git:
      url: https://github.com/easemob/im_flutter_sdk.git
      ref: flutter2_dev
  ease_call_kit:
    git:
      url: https://github.com/easemob/ease_call_kit.git
      ref: stable

D/ONE SDK (12958): [2021/09/03 13:54:51:066]: update baseServiceUrl: https://mserver.easemob.com:443
D/ONE SDK (12958): [2021/09/03 13:54:51:066]: update configInfo
D/ONE SDK (12958): [2021/09/03 13:54:51:066]: getConfigInfoWithVersion() version : 3.8.3
D/ONE SDK (12958): [2021/09/03 13:54:51:066]: getBaseServerUrl()
D/ONE SDK (12958): [2021/09/03 13:54:51:066]: checkDNS finished
D/ONE SDK (12958): [2021/09/03 13:54:51:067]: httprequest perform: https://mserver.easemob.com:443/api/v1/sdk/config?appkey=1152210826175377%23demo&version=3.8.3
D/ONE SDK (12958): [2021/09/03 13:54:51:068]: EMDNSManager::getHost: type: 2
D/ONE SDK (12958): [2021/09/03 13:54:51:069]: current host: domain: 39.97.193.95 port: 12002
D/ONE SDK (12958): [2021/09/03 13:54:51:069]: token is valid
D/ONE SDK (12958): [2021/09/03 13:54:51:069]: token status:  0
D/ONE SDK (12958): [2021/09/03 13:54:51:069]: setServer: 39.97.193.95
D/ONE SDK (12958): [2021/09/03 13:54:51:069]: Calling connect...
D/ONE SDK (12958): [2021/09/03 13:54:51:073]: doConnect()
D/ONE SDK (12958): [2021/09/03 13:54:51:073]: current connectState: 0
D/ONE SDK (12958): [2021/09/03 13:54:51:073]: log: level: 2, area: 1, ChatClient::connect() 
D/ONE SDK (12958): [2021/09/03 13:54:51:073]: log: level: 0, area: 2, getSocket(): 70
D/ONE SDK (12958): [2021/09/03 13:54:51:073]: log: level: 1, area: 2, connectSocket(): start to connecting...
W/System.err(12958): java.lang.NumberFormatException: For input string: "mserver"

**Comment by dujiepeng** [comment]
@xiayanping 您好，这个不影响您那边使用，这个已经被安卓sdk catch住了，但是目前仍有打印，后续版本安卓sdk升级后会把打印去掉。
