### ISSUE TITLE
type 'WhereIterable<String?>' is not a subtype of type 'List<String>' in type cast

### ISSUE THREAD

**Issue by xiayanping** [easemob/im_flutter_sdk#409]
![image](https://user-images.githubusercontent.com/6671396/132374812-d6838092-fa4f-4675-9f3d-502dafe032c8.png)

 im_flutter_sdk:
    git:
      url: https://github.com/easemob/im_flutter_sdk.git
      ref: flutter2_dev
  ease_call_kit:
    git:
      url: https://github.com/easemob/ease_call_kit.git
      ref: stable

environment:
  sdk: ">=2.12.0 <3.0.0"

**Comment by dujiepeng** [comment]
已经修复了，请拉取最新的flutter2_dev

**Comment by xiayanping** [comment]
![image](https://user-images.githubusercontent.com/6671396/132516229-1077c824-7875-433c-8e60-ded7645572fc.png)


还是不行呀，我看其它版本都是toList
