### ISSUE TITLE
EMClient.getInstance.groupManager.requestToJoinPublicGroup  报一个空异常

### ISSUE THREAD

**Issue by clstech** [easemob/im_flutter_sdk#426]
在使用 EMClient.getInstance.groupManager.requestToJoinPublicGroup 加群时候 报一个空异常

W/IInputConnectionWrapper(23133): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(23133): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(23133): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(23133): getTextAfterCursor on inactive InputConnection
D/ONE SDK (23133): [2021/09/10 16:55:11:884]: nativeFetchPublicGroupsWithCursor
D/ONE SDK (23133): [2021/09/10 16:55:11:885]: current host: domain: a2-v2.easemob.com port: 443
D/ONE SDK (23133): [2021/09/10 16:55:11:885]: httprequest perform: https://a2-v2.easemob.com:443/1121210420180008/clsdzq/publicchatgroups?version=v3&resource=android_da094b0e-ecbd-3741-a3ef-0c83a3e77154&limit=200
D/ONE SDK (23133): [2021/09/10 16:55:12:193]: fetchMucsByCursor:: cursor:  pageSize: 200 isPublic: 1 retCode: 200
D/ONE SDK (23133): [2021/09/10 16:55:12:223]: callback getNetState
D/ONE SDK (23133): [2021/09/10 16:55:12:227]: current host: domain: a2-v2.easemob.com port: 443
D/ONE SDK (23133): [2021/09/10 16:55:12:227]: httprequest perform: https://a2-v2.easemob.com:443/1121210420180008/clsdzq/chatgroups/159241624158209?version=v3&resource=android_da094b0e-ecbd-3741-a3ef-0c83a3e77154
D/ONE SDK (23133): [2021/09/10 16:55:12:557]: fetchMucSpecification:: retCode: 200
D/FirebaseInstanceId(23133): background sync failed: SERVICE_NOT_AVAILABLE, retry in 40s
D/FirebaseInstanceId(23133): background sync failed: SERVICE_NOT_AVAILABLE, retry in 80s
D/ONE SDK (23133): [2021/09/10 16:56:54:345]: log: level: 1, area: 1, NO unread queue, an response for ping?
D/ONE SDK (23133): [2021/09/10 16:56:54:346]: native_1sendPing
D/FirebaseInstanceId(23133): background sync failed: SERVICE_NOT_AVAILABLE, retry in 160s
D/ONE SDK (23133): [2021/09/10 16:59:40:448]: log: level: 1, area: 1, NO unread queue, an response for ping?
D/ONE SDK (23133): [2021/09/10 16:59:40:448]: native_1sendPing
D/FirebaseInstanceId(23133): background sync failed: SERVICE_NOT_AVAILABLE, retry in 320s
D/ONE SDK (23133): [2021/09/10 17:00:22:311]: callback getNetState
D/ONE SDK (23133): [2021/09/10 17:00:22:316]: current host: domain: a2-v2.easemob.com port: 443
D/ONE SDK (23133): [2021/09/10 17:00:22:316]: httprequest perform: https://a2-v2.easemob.com:443/1121210420180008/clsdzq/chatgroups/159241624158209?version=v3&resource=android_da094b0e-ecbd-3741-a3ef-0c83a3e77154
D/ONE SDK (23133): [2021/09/10 17:00:22:664]: fetchMucSpecification:: retCode: 200
D/ONE SDK (23133): [2021/09/10 17:00:22:667]: callback getNetState
D/ONE SDK (23133): [2021/09/10 17:00:22:673]: current host: domain: a2-v2.easemob.com port: 443
D/ONE SDK (23133): [2021/09/10 17:00:22:673]: httprequest perform: https://a2-v2.easemob.com:443/1121210420180008/clsdzq/chatgroups/159241624158209?version=v3&resource=android_da094b0e-ecbd-3741-a3ef-0c83a3e77154
D/ONE SDK (23133): [2021/09/10 17:00:23:013]: fetchMucSpecification:: retCode: 200
D/ONE SDK (23133): [2021/09/10 17:00:23:013]: current host: domain: a2-v2.easemob.com port: 443
D/ONE SDK (23133): [2021/09/10 17:00:23:013]: httprequest perform: https://a2-v2.easemob.com:443/1121210420180008/clsdzq/chatgroups/159241624158209/apply?version=v3&resource=android_da094b0e-ecbd-3741-a3ef-0c83a3e77154
D/ONE SDK (23133): [2021/09/10 17:00:23:332]: mucApply:: retCode: 200
D/ONE SDK (23133): [2021/09/10 17:00:23:333]: mucApply:: joinGroup: group id : 159241624158209errorCode : 0errorDetail
E/AndroidRuntime(23133): FATAL EXCEPTION: pool-10-thread-5
E/AndroidRuntime(23133): Process: cn.clstech.clsim, PID: 23133
E/AndroidRuntime(23133): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.hyphenate.chat.EMGroup.getGroupId()' on a null object reference
E/AndroidRuntime(23133): 	at com.easemob.im_flutter_sdk.EMGroupHelper.toJson(EMHelper.java:148)
E/AndroidRuntime(23133): 	at com.easemob.im_flutter_sdk.EMGroupManagerWrapper$22.onSuccess(EMGroupManagerWrapper.java:662)
E/AndroidRuntime(23133): 	at com.hyphenate.chat.EMGroupManager$13.run(Unknown Source:9)
E/AndroidRuntime(23133): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(23133): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(23133): 	at java.lang.Thread.run(Thread.java:923)
E/CrashReport(23133): Java Crash Happen cause by pool-10-thread-5(20264)
W/CrashReport(23133): no read_log permission!
I/CrashReport(23133): user log size:0
E/CrashReport(23133): stack frame :6, has cause false
E/CrashReport(23133): #++++++++++Record By Bugly++++++++++#
E/CrashReport(23133): # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
E/CrashReport(23133): # PKG NAME: cn.clstech.clsim
E/CrashReport(23133): # APP VER: 1.0.0
E/CrashReport(23133): # SDK VER: 3.4.12(1.5.23)-3.9.0
E/CrashReport(23133): # LAUNCH TIME: 2021-09-10 16:54:53
E/CrashReport(23133): # CRASH TYPE: JAVA_CRASH
E/CrashReport(23133): # CRASH TIME: 2021-09-10 17:00:23
E/CrashReport(23133): # CRASH PROCESS: cn.clstech.clsim
E/CrashReport(23133): # CRASH THREAD: pool-10-thread-5
E/CrashReport(23133): # REPORT ID: dc25cb43-608f-4e44-a684-5b8b2482f276
E/CrashReport(23133): # CRASH DEVICE: M2102K1C UNROOT
E/CrashReport(23133): # RUNTIME AVAIL RAM:4543393792 ROM:110023634944 SD:110023634944
E/CrashReport(23133): # RUNTIME TOTAL RAM:11790438400 ROM:241904365568 SD:241904365568
E/CrashReport(23133): # CRASH STACK: 
E/CrashReport(23133): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.hyphenate.chat.EMGroup.getGroupId()' on a null object reference
E/CrashReport(23133): 	at com.easemob.im_flutter_sdk.EMGroupHelper.toJson(EMHelper.java:148)
E/CrashReport(23133): 	at com.easemob.im_flutter_sdk.EMGroupManagerWrapper$22.onSuccess(EMGroupManagerWrapper.java:662)
E/CrashReport(23133): 	at com.hyphenate.chat.EMGroupManager$13.run(Unknown Source:9)
E/CrashReport(23133): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CrashReport(23133): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CrashReport(23133): 	at java.lang.Thread.run(Thread.java:923)
E/CrashReport(23133): #++++++++++++++++++++++++++++++++++++++++++#
D/CrashReport(23133): [Database] deleted t_lr data 1
D/CrashReport(23133): [Database] insert t_lr success.
I/CrashReportInfo(23133): [crash] a crash occur, handling...
D/CrashReport(23133): [Database] insert t_cr success.
D/CrashReport(23133): insert t_cr success!
I/CrashReportInfo(23133): [crash] save crash success
I/CrashReport(23133): try to upload right now
D/CrashReport(23133): libInfo null
D/CrashReport(23133): java.lang.NullPointerException rid:dc25cb43-608f-4e44-a684-5b8b2482f276 sess:db7a0028-4649-4214-ae13-ff6d8315b396 ls:329s isR:false isF:true isM:false isN:false mc:0 ,null ,isUp:false ,vm:31
D/CrashReport(23133): [UploadManager] Add upload task (pid=23133 | tid=18812)
D/CrashReport(23133): [UploadManager] Execute synchronized upload task (pid=23133 | tid=18812)
D/CrashReport(23133): [Upload] Run upload task with cmd: 830
D/CrashReport(23133): [Util] Zip 11254 bytes data with type Gzip
D/CrashReport(23133): [Database] deleted t_lr data 1
D/CrashReport(23133): [Database] insert t_lr success.
D/CrashReport(23133): [UploadManager] Uploading(ID:1004) time: 2021-09-10 17:00:23
D/CrashReport(23133): [Upload] Send 2148 bytes
D/CrashReport(23133): [Upload] Upload to https://android.bugly.qq.com/rqd/async?aid=2ddeae76-c40f-434a-be37-b32641ebf90a with cmd 830 (pid=23133 | tid=18896).
D/CrashReport(23133): request: https://android.bugly.qq.com/rqd/async?aid=2ddeae76-c40f-434a-be37-b32641ebf90a, send: 2148 (pid=23133 | tid=18896)
D/CrashReport(23133): checkServerTrusted
D/CrashReport(23133): [Upload] Bugly version from headers is: bugly/1.0
D/CrashReport(23133): [Upload] Status from server is 0 (pid=23133 | tid=18896).
D/CrashReport(23133): [Upload] Received 95 bytes
D/CrashReport(23133): [Util] Unzip 95 bytes data with type Gzip
W/CrashReport(23133): Not in GZIP format
D/CrashReport(23133): [Upload] Response cmd is: 0, length of sBuffer is: 0
I/CrashReport(23133): [Upload] Success: crash
D/CrashReport(23133): [UploadManager] Local network consume: 65 KB
D/CrashReport(23133): [Database] deleted t_lr data 1
D/CrashReport(23133): [Database] insert t_lr success.
D/CrashReport(23133): [UploadManager] Network total consume: 67 KB
D/CrashReport(23133): up finish update state true
D/CrashReport(23133): pre uid:dc25cb43-608f-4e44-a684-5b8b2482f276 uc:0 re:false me:false
D/CrashReport(23133): set uid:dc25cb43-608f-4e44-a684-5b8b2482f276 uc:1 re:true me:false
D/CrashReport(23133): [Database] insert t_cr success.
D/CrashReport(23133): insert t_cr success!
D/CrashReport(23133): update state size 1
E/CrashReport(23133): sys default last handle start!
D/CrashReport(23133): >>> cn.clstech.clsim.MainActivity onPaused <<<
I/CrashReport-Native(23133): jni_setNativeInfo: key is 14
I/CrashReport-Native(23133): Set native info: isAppForeground(false)
I/Process (23133): Sending signal. PID: 23133 SIG: 9
Lost connection to device.

**Comment by dujiepeng** [comment]
@lzdtech 你好，这个问题目前没有重现出来，能提供些其他信息么，比如这个群是否存在，加入是否成功等。

**Comment by dujiepeng** [comment]
已修复。
