### ISSUE TITLE
调用fetchHistoryMessages报错

### ISSUE THREAD

**Issue by tongdong** [easemob/im_flutter_sdk#429]
![图片](https://user-images.githubusercontent.com/12770291/133737643-76e1bec7-c240-4a5d-8dce-59482e80c656.png)
![图片](https://user-images.githubusercontent.com/12770291/133737682-3e361494-bda6-4b80-b542-5db1c891408e.png)

**Comment by dujiepeng** [comment]
@tongdong 你好，这个报错目前没有重现，能提供下调用的上下文么？ 看着感觉是返回的是EMCursorResult<Message?>, 但调用的时候是EMCursorResult<Message> result =  EMClient.xxxxx 了。 您flutter的版本是？
