### ISSUE TITLE
会话里的群聊都只是显示群聊ID而已?

### ISSUE THREAD

**Issue by ZackTvZ** [easemob/im_flutter_sdk#433]
@dujiepeng @dujiepeng 如图显示 是我少做什么东西了吗?
![Screenshot 2021-09-21 at 4 18 57 PM (2)](https://user-images.githubusercontent.com/4057779/134137170-4d7f888e-c958-49a3-a1c4-57ea55e57b85.png)

**Comment by dujiepeng** [comment]
@ZackTvZ  是的会话列表里只有会话id，如果需要显示其他，需要显式的设置，目前conversation提供了name属性，可以setName;

**Comment by ZackTvZ** [comment]
那么在create group的时候 收消息方面要怎样那么group name?

**Comment by dujiepeng** [comment]
@ZackTvZ 这个之和会话有关，demo是在从群列表进入会话会话的时候做了set name的操作。如果是接收消息，也一样是需要先获取群属性，之和进行set name.

**Comment by ZackTvZ** [comment]
接收方 如何第一次收到信息的时候 setname呢 是收到信息后? 还是什么时候
