### ISSUE TITLE
请问什么时候适配null safe?

### ISSUE THREAD

**Issue by cjl84914** [easemob/im_flutter_sdk#434]
工程有些插件还不是null safe, 例如：keyboard_visibility: 0.5.6

**Comment by dujiepeng** [comment]
@cjl84914 你好，sdk已经支持了，demo暂时没有办法完全支持。

**Comment by takeeasyman** [comment]
![image](https://user-images.githubusercontent.com/3069003/140895607-f5c83fe0-57b9-4ee3-b0d5-354b367cdaee.png)

**Comment by dujiepeng** [comment]
@z870248707  可以使用flutter2_stable分支。

**Comment by takeeasyman** [comment]
> @z870248707 可以使用flutter2_stable分支。

好的，谢谢
