### ISSUE TITLE
发出去的消息一直转圈

### ISSUE THREAD

**Issue by tongdong** [easemob/im_flutter_sdk#435]
![图片](https://user-images.githubusercontent.com/12770291/134809083-7f1dd584-7f0a-4983-95ad-793e75958cda.png)

await EMClient.getInstance.chatManager.sendMessage(msg);发送消息的localTime和ChatItem的localTime对不上，导致ChatItem收不到回调，请问这个情况需要怎么处理

**Comment by dujiepeng** [comment]
@tongdong 你好，这个我暂时没有重现，有具体的重现步骤么。

**Comment by tongdong** [comment]
把
![图片](https://user-images.githubusercontent.com/12770291/134842663-43fcf15d-f35c-4a7f-ab86-2ce35e34867e.png)
反转一下

![图片](https://user-images.githubusercontent.com/12770291/134842710-40081a6e-dfb6-4d10-ada1-20b6a01e2e0d.png)
把发送的新消息插到第一位， 就能复现了

**Comment by tongdong** [comment]
因为想要结合pull_to_refresh做聊天页的下拉加载 需要倒序 发现消息一直转圈

**Comment by dujiepeng** [comment]
@tongdong 看下chat_item中添加监听的位置，把setMessageListener移动到build中试下。
