### ISSUE TITLE
登陆后出现链接问题

### ISSUE THREAD

**Issue by bxvip** [easemob/im_flutter_sdk#436]
E/EMClient(27486): hyphenate SDK is initialized with version : 3.8.3
D/ONE SDK (27486): [2021/09/27 17:03:18:046]: sqlite version: 3.26.0
D/ONE SDK (27486): [2021/09/27 17:03:18:046]: performMigrationIfNecessary current DB version: 6
D/ONE SDK (27486): [2021/09/27 17:03:18:049]: Java_com_hyphenate_chat_adapter_EMAChatManager_nativeLoadAllConversationsFromDB
D/ONE SDK (27486): [2021/09/27 17:03:18:051]: msgList.size2
D/ONE SDK (27486): [2021/09/27 17:03:18:052]: conversationMap.size:5
D/ONE SDK (27486): [2021/09/27 17:03:18:053]: [EMClient] emchat manager login in process:27486
D/ONE SDK (27486): [2021/09/27 17:03:18:054]: [EMClient] emchat manager login in process:27486 threadName:pool-11-thread-2 ID:7132
D/ONE SDK (27486): [2021/09/27 17:03:18:054]: performMigrationIfNecessary current DB version: 6
D/ONE SDK (27486): [2021/09/27 17:03:18:054]: autoLogin
D/ONE SDK (27486): [2021/09/27 17:03:18:054]: EMSessionManager::login(): is autoLogin? 1, id: fd2fc5d75f60a203fa4ea8df30ec6a51
D/ONE SDK (27486): [2021/09/27 17:03:18:054]: os version: 11
D/ONE SDK (27486): [2021/09/27 17:03:18:056]: current host: domain: mserver.easemob.com port: 443
D/ONE SDK (27486): [2021/09/27 17:03:18:056]: current host: domain: 121.36.14.4 port: 6717
D/ONE SDK (27486): [2021/09/27 17:03:18:057]: httprequest perform: https://mserver.easemob.com:443/api/v1/sdk/config?appkey=xxxxx%23fxxx&version=3.8.3
D/ONE SDK (27486): [2021/09/27 17:03:18:057]: token status:  0
D/ONE SDK (27486): [2021/09/27 17:03:18:058]: log: level: 2, area: 1, ChatClient::connect() 
D/ONE SDK (27486): [2021/09/27 17:03:18:058]: log: level: 1, area: 2, connectSocket(): start to connecting...
W/System.err(27486): java.lang.NumberFormatException: For input string: "mserver"
W/System.err(27486): 	at java.lang.Integer.parseInt(Integer.java:615)
W/System.err(27486): 	at java.lang.Integer.parseInt(Integer.java:650)
W/System.err(27486): 	at com.hyphenate.cloud.HttpClientController.a(Unknown Source:63)
W/System.err(27486): 	at com.hyphenate.cloud.HttpClientController.a(Unknown Source:1)
W/System.err(27486): 	at com.hyphenate.cloud.HttpClientController$HttpParams.apply(Unknown Source:13)
W/System.err(27486): 	at com.hyphenate.cloud.HttpClientManager$Builder.build(Unknown Source:11)
W/System.err(27486): 	at com.hyphenate.cloud.HttpClientManager$Builder.executePrivate(Unknown Source:4)
W/System.err(27486): 	at com.hyphenate.cloud.HttpClientManager$Builder.executeNormal(Unknown Source:0)
W/System.err(27486): 	at com.hyphenate.cloud.HttpClientManager$Builder.execute(Unknown Source:13)
W/System.err(27486): 	at com.hyphenate.cloud.HttpClientManager$Builder.execute(Unknown Source:1)
W/System.err(27486): 	at com.hyphenate.cloud.HttpClientManager.httpExecute(Unknown Source:38)
W/System.err(27486): 	at com.hyphenate.cloud.HttpClientManager.httpExecute(Unknown Source:4)
W/System.err(27486): 	at com.hyphenate.chat.adapter.EMARHttpAPI._httpExecute(Unknown Source:0)
W/System.err(27486): 	at com.hyphenate.chat.adapter.EMARHttpAPI.httpExecute(Unknown Source:4)
I/DpmTcmClient(27486): RegisterTcmMonitor from: $Proxy1

**Comment by dujiepeng** [comment]
@bxvip 有更明确的报错么。
