### ISSUE TITLE
注册监听聊天室监听，无法收到回调

### ISSUE THREAD

**Issue by AidanFreeman** [easemob/im_flutter_sdk#439]
![image](https://user-images.githubusercontent.com/58162973/136612729-59af42ec-d477-4c2f-ac04-df23c38f1e1b.png)
![image](https://user-images.githubusercontent.com/58162973/136613051-c31e7ed6-cfea-4508-aa4f-557e50225d3d.png)
ru如图，可以看到sdk里面输出了回调，但是本地无法收到，请问下哪里有什么问题，版本stable 3.8.3 
![image](https://user-images.githubusercontent.com/58162973/136613150-3e251121-269d-4d7a-ab07-795757c56971.png)
![image](https://user-images.githubusercontent.com/58162973/136613244-bb1ce6aa-9911-46e0-a066-72abdf6e489b.png)
最后的ri日志也没输出

**Comment by dujiepeng** [comment]
@AidanFreeman  你注册监听的代码是在sdk初始化后执行的么。

**Comment by dujiepeng** [comment]
没有新的反馈，暂时关闭。
