### ISSUE TITLE
sdk还没有支持空安全

### ISSUE THREAD

**Issue by wangye888** [easemob/im_flutter_sdk#440]
<img width="578" alt="截屏2021-10-14 下午8 32 25" src="https://user-images.githubusercontent.com/92528784/137327986-801ad29a-057e-4072-be21-9987f6e692fe.png">

**Comment by wangye888** [comment]
![截屏2021-10-14 下午8 33 33](https://user-images.githubusercontent.com/92528784/137328347-96381a64-4d3f-4ae3-95f1-c18d6a61277a.png)

**Comment by dujiepeng** [comment]
@wangye888 可以使用flutter2_dev分支。
