### ISSUE TITLE
一直报 errorCode 2

### ISSUE THREAD

**Issue by jianibaobei** [easemob/im_flutter_sdk#446]
一直报 errorCode 2
EaseMob | V | init: {appKey: 1113200703041339#blinddate, autoLogin: true, debugModel: true, acceptInvitationAlways: false, autoAcceptGroupInvitation: false, deleteMessagesAsExitGroup: true, deleteMessagesAsExitChatRoom: true, dnsUrl: , enableDNSConfig: true, imPort: 0, imServer: , isAutoDownload: true, isChatRoomOwnerLeaveAllowed: true, requireAck: true, requireDeliveryAck: false, restServer: , serverTransfer: true, sortMessageByServerTime: true, usingHttpsOnly: false}
E/EMPushConfig(25463): senderId can't be empty when enable FCM push !
E/EMPushHelper(25463): EMPushHelper init, config: EMPushConfig{fcmSenderId='null', hwAppId='null', miAppId='null', miAppKey='null', mzAppId='null', mzAppKey='null', oppoAppKey='null', oppoAppSecret='null', vivoAppId='null', vivoAppKey='null', enabledPushTypes=[]}
D/ONE SDK (25463): [2021/11/04 11:13:49:412]: set temporary sampling rate
D/ONE SDK (25463): [2021/11/04 11:13:49:412]: getConfigInfoWithVersion() version : 3.8.3
D/ONE SDK (25463): [2021/11/04 11:13:49:412]: addConnectionListener
D/ONE SDK (25463): [2021/11/04 11:13:49:412]: getBaseServerUrl()
D/ONE SDK (25463): [2021/11/04 11:13:49:412]: monitorBaseUrl()
D/ONE SDK (25463): [2021/11/04 11:13:49:412]: EMDNSManager::getCurrentHost: type: 4
D/ONE SDK (25463): [2021/11/04 11:13:49:412]: EMDNSManager::getHost: type: 4
D/ONE SDK (25463): [2021/11/04 11:13:49:412]: getBaseServerUrl() , monitorBaseUrl : 
D/ONE SDK (25463): [2021/11/04 11:13:49:412]: url is invalid
D/ONE SDK (25463): [2021/11/04 11:13:49:415]: addConnectionListener
D/ONE SDK (25463): [2021/11/04 11:13:49:420]: registerContactListener
E/EMClient(25463): is autoLogin : true
E/EMClient(25463): lastLoginUser : 
E/EMClient(25463): hyphenate SDK is initialized with version : 3.8.3
I/flutter (25463): isConnected=false
I/flutter (25463): onDisconnected，errorCode==2

**Comment by dujiepeng** [comment]
static final int | NETWORK_ERROR = 2
2看起来是网络错误，请问是必现的么。可以加群535134817

**Comment by dujiepeng** [comment]
没有新的反馈，暂时关闭。
