### ISSUE TITLE
iOS离线推送有的账号可以收到推送，有的收不到

### ISSUE THREAD

**Issue by HuberCui** [easemob/im_flutter_sdk#465]
如标题，跑了一下官方demo也是如此问题

**Comment by HuberCui** [comment]
发现杀死进程，还是走的环信推送，没有走APNS推送，应该是这个原因，怎么解决呢？

**Comment by dujiepeng** [comment]
如果app被杀死进程，此时收到的消息会通过apns通知，之后用户上线后会通过sdk的收消息回调接收消息，这个是正常现象。 “离线推送有的能收到，有的收不到”这个可以具体描述下么？

**Comment by HuberCui** [comment]
> 

刚才试了一下，在杀死进程的环境下，我用环信后台手动推送，通道策略默认 [“环信通道优先，在线走环信，离线走厂商”，走的是环信，选择了三方厂商策略，就走了APns推送，推测是杀死进程，长链接没有断开

- [ ]

**Comment by cjl84914** [comment]
iOS用开发和生产结合的推送证书，离线都能收到推送。
