### ISSUE TITLE
获取不到用户属性

### ISSUE THREAD

**Issue by panzhoutao** [easemob/im_flutter_sdk#480]
EMClient.getInstance.userInfoManager.fetchOwnInfo()；

**Comment by panzhoutao** [comment]
更新属性也不行

**Comment by panzhoutao** [comment]
![image](https://user-images.githubusercontent.com/20410075/150388642-f9150ce7-7fe4-4a15-8181-5aa67f19fb34.png)

**Comment by dujiepeng** [comment]
@panzhoutao 提供下设置和获取的代码。

**Comment by panzhoutao** [comment]
> @panzhoutao 提供下设置和获取的代码。

await EMClient.getInstance.userInfoManager
          .updateOwnUserInfoWithType(EMUserInfoType.NickName, '测试测试')；

await EMClient.getInstance.userInfoManager.fetchOwnInfo()；

**Comment by panzhoutao** [comment]
> @panzhoutao 提供下设置和获取的代码。

已加qq群，但是没通过
