### ISSUE TITLE
demo里，聊天界面表情键盘切换文字输入会闪屏，系统键盘会将表情顶起

### ISSUE THREAD

**Issue by swiftlyfish** [easemob/im_flutter_sdk#484]

**Comment by dujiepeng** [comment]
@ShellPeng 哪个端？  我这边测试的正常。

**Comment by swiftlyfish** [comment]
iOS 你点击表情按钮和 输入框按钮快速切换，或者第一次点击会出现这个情况


彭鹏
***@***.***


签名由 网易邮箱大师 定制



在2022年03月10日 ***@***.***> 写道：


@ShellPeng 哪个端？ 我这边测试的正常。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
