### ISSUE TITLE
无法在离线时收到好友请求

### ISSUE THREAD

**Issue by Linspirit98** [easemob/im_flutter_sdk#491]
当用户A给用户B发送好友请求之后，当app在线时，会调用onContactInvited. 但是当用户B是离线状态时，打开app后也没有缓存好友请求，这个正常吗？而且app离线的时候也没有收到好友请求相关的推送。

**Comment by xiaofengin** [comment]
可能原因：当你下次打开APP 登录成功之后会触发收到好友请求的回调 如果这个时候 你没有添加监听 可能就会丢失 
解决方法：在你登录成功之前直接就添加好友请求监听

**Comment by dujiepeng** [comment]
@15617665365 新版本sdk中有一个startCallback的方法，调用之前不会回调，ui准备好调用这个，sdk就会向上层回调了。
