### ISSUE TITLE
获取msgTime报错

### ISSUE THREAD

**Issue by ixre** [easemob/im_flutter_sdk#501]
E/AndroidRuntime( 1874): java.lang.NullPointerException: Attempt to invoke virtual method 'long com.hyphenate.chat.EMMessage.getMsgTime()' on a null object reference
E/AndroidRuntime( 1874): 	at com.easemob.im_flutter_sdk.EMChatManagerWrapper$5.compare(EMChatManagerWrapper.java:413)

**Comment by dujiepeng** [comment]
你好，请问是哪个版本。

**Comment by ixre** [comment]
最新

**Comment by dujiepeng** [comment]
@ixre 3.9.0+1 还是stable？

**Comment by ixre** [comment]
引用的源代码
