### ISSUE TITLE
EMMessage的status变更是不是有问题？

### ISSUE THREAD

**Issue by abellee** [easemob/im_flutter_sdk#503]
看了一下源码，消息状态是在`MessageStatusCallback`里改的
也就是说，`sendMessage`后，如果不`setMessageStatusCallback`的话，消息的状态是得不到即时更新的。
是不是有问题

**Comment by dujiepeng** [comment]
@abellee 因为flutter这一侧除了发送消息其他的都是从原生sdk去取，sdk内部这个状态是更新的。所以这个状态从sdk获取时会是正确的。

**Comment by abellee** [comment]
@dujiepeng 但是如果我不`setMessageStatusCallback` 直接获取状态，那状态就一直是`onProgress`的，
场景是：通过消息的状态来判断是否显示一个loading的动画图标，但做一个延迟(毫秒级)的状态检测，如果仍处在发送中，则显示loading，否则就不显示。
我觉得Flutter侧不应该纠结原生SDK，这样的处理也是有问题的，不论是否有回调，消息状态是必须要更新的吧。

**Comment by dujiepeng** [comment]
@abellee 你说的这个场景是需要设置statusCallback的。
你说的情况我非常同意，之前有一个版本是按照这个实现的，但是flutter中消息结构都是new出来的，如果sdk直接持有了消息，它和ui上持有的很可能不是一份(因为ui更新时可能会重新从sdk load，而load出来的都是new的)。这就导致sdk更新了消息状态，你持有的不会更新。所以必须要求你显式的把这个callback设置给sdk，sdk才能才得到回调时更新你持有的。

另外，也有考虑把整个消息状态提高，从现在的针对message 的callback放到EMChatManager这个级别，但目前原生那边不保留messageId，也就是说消息发送的时候是messageid是1，发送成功后就直接变成了2，没有对应关系，这就会导致提到EMChatManager后，无法对应是哪一条消息发送成功。所以目前只能这样实现，我也和原生同步了这个情况，也期待他们有这个处理。

**Comment by abellee** [comment]
@dujiepeng 感谢
