### ISSUE TITLE
消息不回调

### ISSUE THREAD

**Issue by abellee** [easemob/im_flutter_sdk#512]
![CleanShot 2022-05-24 at 11 12 25](https://user-images.githubusercontent.com/707615/169941338-d2a13aaa-3137-4014-aa68-8a10e594372b.png)
请问一下 这样初始化过程有没有问题？为什么消息回调时有时无的，然后等突然收到的时候就一下收到七八条，看console是有输出日志的 但是sdk就是不回调。

每次add前的remove是为了避免虚拟机多次监听的，但也试过去掉 或者startCallback放到具体界面 都不行，而且我是在用户登陆后初始化的，基本上已经经过很多个界面切换了。

再者是 比较新消息的通知也是，文档里说离线消息在上线后会再次回调，也是时有时无的。

麻烦尽快帮忙解答一下，项目卡这挺久了，官网后台也发了工单 不知道有没有人 - -！！

**Comment by dujiepeng** [comment]
@abellee 看起来没问题，这个类是哪里用的，方便的话可以把这个文件完整的代码提供下。

**Comment by abellee** [comment]
@dujiepeng 这个文件里剩余的部分 就全部都是相关的监听回调 没有别的代码了，用是在另外一个单例里 用户登陆之后调用，但如果用户已经登陆过了 再重新进入app的时候 会在runApp之前就被初始化 所以是不是这种情况下是有问题的

**Comment by abellee** [comment]
@dujiepeng 可能已经解决了，我在`reassemble`里移除了所有监听，并在`build`里重新监听，好像是正常了，但这也只能确保热重载的情况下 热重启还是会有问题，得再次保存一下触发热重载。但是 能否优化一下开发模式下的体验，这真的有点头大，我还得专门为开发模式下搞一套逻辑。
因为你demo里的都是在对应的界面里进行注册监听的 然后`dispose`的时候取消监听（这里我也有点奇怪，貌似hot reload的时候是不会触发`dispose`的），可能不太会有我这方面的问题，但如果用单例，那真的就各种莫名其妙了
