### ISSUE TITLE
There is  no HyphenateChat (= 3.9.3.1) in CocoaPods

### ISSUE THREAD

**Issue by timzaak** [easemob/im_flutter_sdk#515]
Only have HyphenateChat (= 3.9.3) , please upload it.

**Comment by dujiepeng** [comment]
@timzaak 
-> HyphenateChat (3.9.4)
   An Objective-C client for IM service
   pod 'HyphenateChat', '~> 3.9.4'
   - Homepage: http://www.easemob.com/
   - Source:   https://downloadsdk.easemob.com/downloads/HyphenateChat3_9_4.zip
   - Versions: 3.9.4, 3.9.3.1, 3.9.3, 3.9.2.1, 3.9.2, 3.9.1.1, 3.9.1, 3.9.0.1, 3.9.0, 3.8.9.2, 3.8.9.1, 3.8.9, 3.8.8,
   3.8.7.3, 3.8.7, 3.8.6.3, 3.8.6.2, 3.8.6, 3.8.5.2, 3.8.5.1, 3.8.5, 3.8.4, 3.8.3.1, 3.8.3, 3.8.2, 3.8.1, 3.8.0, 0.1.0
   [trunk repo]
   
  here i found 3.9.3.1 version.

**Comment by timzaak** [comment]
I'm sorry, I should run `pop update HyphenateChat` firstly, then run `flutter run`. 

But  `EMClient.getInstance.pushManager.updatePushDisplayStyle(DisplayStyle.Simple);` would be error, DisplayStyle does not be exported.

**Comment by dujiepeng** [comment]
@timzaak 
u r right,i found this issue too.  it's will fix in next version. in 3.9.3 version, push was not good,  the new version should will change methods. so if you are  no hurry, please wait the new version. it’s plan in next weekend.

**Comment by timzaak** [comment]
@dujiepeng , thanks for your reply and patient.

**Comment by dujiepeng** [comment]
@timzaak the plan is delay, cause of ios version have bugs. i will urge ios release new verison. then flutter can release on 3.9.5.  the new api in flutter2_dev branch, you can try it first.
