### ISSUE TITLE
Whether to support the web version

### ISSUE THREAD

**Issue by zhongmengfeng** [easemob/im_flutter_sdk#517]
I want to add the fluuter im component to vue, is it feasible

**Comment by dujiepeng** [comment]
@zhongmengfeng  hi, we don't support web platform so far. but we have web sdk, if you want try it. please visit https://github.com/easemob/webim

**Comment by zhongmengfeng** [comment]
thank you for your reply




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月13日 16:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [easemob/im_flutter_sdk] Whether to support the web version (Issue #517) |

hi, we don't support web platform so far. but we have web sdk, if you want try it. please visit https://github.com/easemob/webim
