### ISSUE TITLE
支持音视频了吗？

### ISSUE THREAD

**Issue by zhanchi88** [easemob/im_flutter_sdk#58]
现在是发布版还是测试版？

**Comment by dujiepeng** [comment]
尽请期待。



---原始邮件---
发件人: "小翅"<notifications@github.com&gt;
发送时间: 2019年11月27日(星期三) 晚上9:59
收件人: "easemob/im_flutter_sdk"<im_flutter_sdk@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [easemob/im_flutter_sdk] 支持音视频了吗？ (#58)



现在是发布版还是测试版？

**Comment by naizhu** [comment]
没文档啊

**Comment by bingo** [comment]
https://easemob.github.io/im_flutter_sdk/  暂时只有SDK API 文档。
