### ISSUE TITLE
请问什么时候放到pub上

### ISSUE THREAD

**Issue by huangqiang325** [easemob/im_flutter_sdk#70]
谢谢

**Comment by vhbvb** [comment]
同问

**Comment by dujiepeng** [comment]
已经在处理了。



---原始邮件---
发件人: "vhbvb"<notifications@github.com&gt;
发送时间: 2019年12月13日(周五) 下午4:17
收件人: "easemob/im_flutter_sdk"<im_flutter_sdk@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [easemob/im_flutter_sdk] 请问什么时候放到pub上 (#70)



同问

**Comment by bingo** [comment]
@dujiepeng 这个目前什么状态，我在pub.dev上还没有看到。

**Comment by VanXD** [comment]
@dujiepeng 能放到pub上吗?

**Comment by bingo** [comment]
@VanXD 您好，麻烦让您久等了，pub.dev梯子问题解决，已经上传。
感谢您的支持和理解。
