### ISSUE TITLE
是不是androidx不支持，编译报错：android.support.annotation does not exist

### ISSUE THREAD

**Issue by TimLang** [easemob/im_flutter_sdk#81]
引入im_flutter_sdk后 iOS一切正常，真机也无问题，但是安卓报错，无法通过编译：android.support.annotation does not exist，我看了下是不是不支持androidx。

**Comment by bingo** [comment]
请先参考一下这篇文章，看是不是能解决您的问题：
https://flutter.dev/docs/development/androidx-migration

如果还有问题，请继续反馈。

**Comment by TimLang** [comment]
回复真快！您发的我都设置过的：
org.gradle.jvmargs=-Xmx1536M

android.useAndroidX=true
android.enableJetifier=true
useProguard = true
android.enableR8 = false

期待您的回复。。

**Comment by apex-wang** [comment]
我们目前是用的support库 如果你的项目是androidX的 您这边可以手动去修改一下 将support换成对应androidX的依赖即可  这里需要注意的是 如果你依赖的第三方 也有使用support 也需要一样修改成androidX   这个只是去换一下依赖 不是很麻烦  flutter项目通过Open android module in Android Studio可以打开android项目结构 里面引用加载的第三方builder文件都可以看到 直接进行修改即可

**Comment by TimLang** [comment]
> 我们目前是用的support库 如果你的项目是androidX的 您这边可以手动去修改一下 将support换成对应androidX的依赖即可 这里需要注意的是 如果你依赖的第三方 也有使用support 也需要一样修改成androidX 这个只是去换一下依赖 不是很麻烦 flutter项目通过Open android module in Android Studio可以打开android项目结构 里面引用加载的第三方builder文件都可以看到 直接进行修改即可

谢谢，我目前的方法是fork下项目，然后把android.support.annotation引用去掉并删除NotNull的注释，后续能有办法解决吗，fork不是个好主意哎，不是安卓工程师，目前不知道有没有其他比较好的办法。

**Comment by apex-wang** [comment]
后面慢慢的肯定都会使用androidx 取代support  我们后面提交代码也会换成androidX的 这样也就不需要用本地fork了  相对的如果客户使用的support 就只能自己先把项目迁移一下 或者 fork到本地自己修改了 这是目前这类问题的现状。
