### ISSUE TITLE
哪个分支的demo能运行啊？我最新版的flutter下载下来完全不能运行啊

### ISSUE THREAD

**Issue by a4081675** [easemob/im_flutter_sdk#82]
![image](https://user-images.githubusercontent.com/17973196/71578799-9ff2ba80-2b34-11ea-882f-b32c38d02483.png)

**Comment by a4081675** [comment]
就是这个错了。
Xcode's output:
↳
    /git/im_flutter_sdk-0c9521dd85bc98db0ee704451cae5f1a776650fc/ios/Classes/EMChatManagerWrapper.m:268:40: error: no known instance method for selector 'loadMessagesWithKeyword:timestamp:count:fromUser:searchDirection:completion:'
        [EMClient.sharedClient.chatManager loadMessagesWithKeyword:keywords
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description

**Comment by dujiepeng** [comment]
有安装cocoapods么？在example中的ios目录下执行pod install

**Comment by a4081675** [comment]
flutter 运行的时候自动执行pod install了吧。刚才我手动执行了一次也不行。
![image](https://user-images.githubusercontent.com/17973196/71580645-805f9000-2b3c-11ea-9c9a-3c93e93f7f23.png)

**Comment by dujiepeng** [comment]
在本地执行一下pod setup 看下，或者在本地pod search Hyphenate， 看下目前本地的ios sdk是什么版本。

**Comment by a4081675** [comment]
![image](https://user-images.githubusercontent.com/17973196/71608729-3a4b1080-2bbe-11ea-97da-1d5bc266f65d.png)

**Comment by a4081675** [comment]
![image](https://user-images.githubusercontent.com/17973196/71610016-505dce80-2bc8-11ea-8052-c98f3f2b6215.png)

**Comment by a4081675** [comment]
-> Hyphenate (3.6.2)
   An Objective-C client for IM service
   pod 'Hyphenate', '~> 3.6.2'
   - Homepage: http://www.easemob.com/
   - Source:  
   https://downloadsdk.easemob.com/downloads/iOS_Pods_IMFullSDK_V3.6.2.zip
   - Versions: 3.6.2, 3.6.1, 3.6.0, 3.5.5, 3.5.4, 3.5.3, 3.5.2, 3.5.1, 3.5.0,
   3.4.3, 3.4.2, 3.4.1, 3.4.0.1, 3.4.0, 3.3.9, 3.3.8, 3.3.7, 3.3.6, 3.3.5,
   3.3.4.1, 3.3.4, 3.3.3, 3.3.2, 3.3.1, 3.3.0, 3.2.3, 3.2.2.2, 3.2.2, 3.2.1,
   3.1.5.1 [master repo]
![image](https://user-images.githubusercontent.com/17973196/71610033-71beba80-2bc8-11ea-9541-982092712c0e.png)

**Comment by dujiepeng** [comment]
恩，前面看是3.6.0，那个时候有的api还没有，你执行过pod setup后，看到的已经到3.6.2了，再手动在runner目录下执行一次，看看可以了么。

**Comment by a4081675** [comment]
执行pod update  好了

**Comment by a4081675** [comment]
im_flutter_sdk.podspec   这个文件里面我觉得加个版本号会好一点

**Comment by dujiepeng** [comment]
@a4081675 好的。
