### ISSUE TITLE
引入库后IOS和Android还需要单独设置什么？

### ISSUE THREAD

**Issue by a4081675** [easemob/im_flutter_sdk#83]
登陆能成功。获取会话为空。用demo的Key和我们的Key都不行。用的IOS模拟器运行的。
Map map = await EMClient.getInstance().chatManager().getAllConversations();
print("map:$map");

输出：map:{}

**Comment by a4081675** [comment]
联系人也能获取成功。会话那个是不是有啥限制啊。比如同一个设备啥的

**Comment by a4081675** [comment]
好了。有会话了，应该是跟着设备走的。重新发了条消息就有了

**Comment by apex-wang** [comment]
会话消息都是本地的 更换设备自然没有之前的记录
