### ISSUE TITLE
example 例子无法运行

### ISSUE THREAD

**Issue by hlj2722** [easemob/im_flutter_sdk#84]
运行环境：
 Android Studio (version 3.5)

Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale zh-CN)
-------------------------------------------------------------

D:\flutter_app\im_flutter_sdk\android\src\main\java\com\easemob\im_flutter_sdk\EMChatRoomManagerWrapper.java:3: ����: �����android.support.annotation������
import android.support.annotation.NonNull;
                                 ^
D:\flutter_app\im_flutter_sdk\android\src\main\java\com\easemob\im_flutter_sdk\EMChatRoomManagerWrapper.java:177: ����: �Ҳ�������
    public void onMethodCall(@NonNull MethodCall methodCall, @NonNull MethodChannel.Result result) {
                              ^
  ����:   �� NonNull
  λ��: �� EMChatRoomManagerWrapper
D:\flutter_app\im_flutter_sdk\android\src\main\java\com\easemob\im_flutter_sdk\EMChatRoomManagerWrapper.java:177: ����: �Ҳ�������
    public void onMethodCall(@NonNull MethodCall methodCall, @NonNull MethodChannel.Result result) {
                                                              ^
  ����:   �� NonNull
  λ��: �� EMChatRoomManagerWrapper
3 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':im_flutter_sdk:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.

**Comment by apex-wang** [comment]
这是提示你项目中有androidX 导致的不兼容  要么把builder.gradle里面的support全部换成androidX的依赖 要么全部换成support  这里要更换的包含项目中依赖的所有第三方库的builder.gradle

**Comment by hlj2722** [comment]
im_flutter_sdk 可以升级到 androidx吗

**Comment by apex-wang** [comment]
这个自己可以把sdk中依赖的support库换成相对应的androidX依赖就行
