### ISSUE TITLE
IOS发送图片消息有问题，Android的没问题。

### ISSUE THREAD

**Issue by a4081675** [easemob/im_flutter_sdk#85]
回调什么的都没有
去IOS那边断点看参数什么的都正常，
[EMClient.sharedClient.chatManager sendMessage:msg
                                          progress:progress
                                        completion:completion];
感觉是这个包有问题。
demo也有这问题

**Comment by TimLang** [comment]
我也发现iOS有这个问题，不知道什么时候能解决。

图片是可以发出去的，但是缺没回调。

**Comment by FuDongHai** [comment]
新更新的dev分支上解决了。

**Comment by bingo** [comment]
@傅东海 已经解决？ 请及时关闭相应的issue

**Comment by dujiepeng** [comment]
请使用stable分支。
