### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by helojo** [easemob/im_flutter_sdk#90]
Compiler message:
../../../../../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)

**Comment by jinxue447461686** [comment]
我也有同样的问题。

**Comment by dujiepeng** [comment]
因为ios demo中用到了
cached_network_image 这个库，这个库需要升级。
在example/pubspec.yaml中改成
cached_network_image: ^2.0.0-rc
