### ISSUE TITLE
大兄弟，你这异步线程直接更新UI啊

### ISSUE THREAD

**Issue by richaelguitar** [easemob/im_flutter_sdk#97]
类EMClientWrapper：
有多处是直接子异步线程直接更新UI,下面以创建账号为例：
    private void createAccount(Object args, Result result) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    JSONObject argMap = (JSONObject) args;
                    String userName = argMap.getString("userName");
                    String password = argMap.getString("password");
                    try {
                        EMClient.getInstance().createAccount(userName, password);
                        onSuccess(result);
                    } catch (HyphenateException e) {
                        onError(result, e);
                    }
                }catch (JSONException e){
                    EMLog.e("JSONException", e.getMessage());
                }
            }
        }).start();

    }

**Comment by apex-wang** [comment]
??大兄弟 那里更新UI了？

**Comment by richaelguitar** [comment]
> ??大兄弟 那里更新UI了？

你这里是开了一个异步线程，然后onSuccess()在flutter的ui线程操作
还是拿注册创建账户这个代码:
 void register(String username, String password){
    _refreshUI(true);
    EMClient.getInstance().createAccount(username, password,
        onSuccess: (){
          Navigator.of(context).pushNamed(Constant.toLoginPage ,arguments:{'username':this._usernameController.text, 'password':this._pwdController.text});
        },
        onError: (code, desc){
          _refreshUI(false);
          switch(code) {
            case 101: {
              WidgetUtil.hintBoxWithDefault('用户ID不合法!');
            }
            break;

            case 102: {
              WidgetUtil.hintBoxWithDefault('用户密码不合                                                                                                           法!');
            }
            break;

            case 203: {
              WidgetUtil.hintBoxWithDefault('用户ID已存在!');
            }
            break;

            case 300: {
              WidgetUtil.hintBoxWithDefault('无法连接服务器!');
            }
            break;

            default: {
              WidgetUtil.hintBoxWithDefault(desc);
            }
            break;
          }
        });
  }
而你的封装接口里面却没有转换到主线程：
public interface EMWrapper {
  default void post(Consumer<Void> func) {
    ImFlutterSdkPlugin.handler.post(new Runnable() {
      @Override
      public void run() {
        func.accept(null);
      }
    });
  }

  default void onSuccess(MethodChannel.Result result) {
      Map<String, Object> data = new HashMap<String, Object>();
      data.put("success", Boolean.TRUE);
      result.success(data);
  }

  default void onError(MethodChannel.Result result, HyphenateException e) {
    Map<String, Object> data = new HashMap<String, Object>();
      data.put("success", Boolean.FALSE);
      data.put("code", e.getErrorCode());
      data.put("desc", e.getDescription());
      result.success(data);
  }
正确的应该是这样：
 default void onSuccess(MethodChannel.Result result) {
    post(Void->{
      Map<String, Object> data = new HashMap<String, Object>();
      data.put("success", Boolean.TRUE);
      result.success(data);
    });
  }

  default void onError(MethodChannel.Result result, HyphenateException e) {
    post(Void->{
      Map<String, Object> data = new HashMap<String, Object>();
      data.put("success", Boolean.FALSE);
      data.put("code", e.getErrorCode());
      data.put("desc", e.getDescription());
      result.success(data);
    });
  }
MethodChanel里面的Result接口所有方法都是在ui线程执行的，
 public interface Result {
        @UiThread
        void success(@Nullable Object var1);

        @UiThread
        void error(String var1, @Nullable String var2, @Nullable Object var3);

        @UiThread
        void notImplemented();
    }

**Comment by apex-wang** [comment]
好的 我们这边看下

**Comment by cv0cv0** [comment]
Android 我也遇到 ui 线程报错了。直接闪退。

**Comment by apex-wang** [comment]
有异常信息 和 具体的堆栈异常吗？

**Comment by cv0cv0** [comment]
@Mygithubyouknow E/AndroidRuntime(13677): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-3
E/AndroidRuntime(13677): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:793)
E/AndroidRuntime(13677): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:726)
E/AndroidRuntime(13677): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:153)
E/AndroidRuntime(13677): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
E/AndroidRuntime(13677): 	at com.easemob.im_flutter_sdk.EMWrapper$-CC.$default$onError(EMWrapper.java:32)
E/AndroidRuntime(13677): 	at com.easemob.im_flutter_sdk.EMPushManagerWrapper.onError(Unknown Source:0)
E/AndroidRuntime(13677): 	at com.easemob.im_flutter_sdk.EMPushManagerWrapper$1.run(EMPushManagerWrapper.java:55)
E/AndroidRuntime(13677): 	at java.lang.Thread.run(Thread.java:764)
I/Process (13677): Sending signal. PID: 13677 SIG: 9

**Comment by cv0cv0** [comment]
@Mygithubyouknow 我是在 App 里运行这一段 EMClient.getInstance().pushManager().enableOfflinePush();
代码的。

**Comment by cv0cv0** [comment]
不过好像不运行这段代码也可以收到推送。

**Comment by apex-wang** [comment]
默认离线推送都是允许的

**Comment by bingo** [comment]
@杜洁鹏 @Mygithubyouknow 这个事情有结论吗？需不需要fix？

**Comment by apex-wang** [comment]
这些都已经改过了 最新的应该没有这些问题了
